### PR TITLE
Add packaging status badge from repology

### PR DESCRIPTION
**Pull request by andersk**
Preview: https://github.com/andersk/ruff/tree/repology-badge#installation

### CODE REVIEW

**Comment by charliermarsh** [comment]
Is there any way to hide the AUR entry, since we have the Arch community entry?

**Comment by charliermarsh** [comment]
Nevermind, I can handle.

**Comment by charliermarsh** [comment]
Looks like it's still being included, but because it's "rolling" rather than "ignored"? Anyway, not a big deal. Thank you!

**Comment by andersk** [comment]
Yeah I didn’t find a way to exclude it without excluding *all* repositories (`?exclude_sources=repository`). There’s a `minversion` parameter but it only changes the color.

**Pull request merged**
