### PR TITLE
Implement `--extend-fixable` option

### LINKED ISSUE #4289: Implement `--extend-fixable` and `--extend-unfixable` variants in CLI
Consider the following ruff config:

```toml
[tool.ruff]
fix = true
unfixable = ["F401", "F841"]
```

F401 and F841 are added as unfixable so that ruff doesn't automatically remove violating lines on file save (it's set up in the editor for autoformat). I do want to enable them in my pre-commit config though. So what I have done is configure the ruff hook like so:

```yaml
      - id: ruff
        name: ruff
        entry: ruff
        args: ["--fixable=F401,F841"]
        require_serial: true
        language: system
        types: [python]
```

However, this makes ruff consider **only** those two codes as fixable. So I thought I could fix it by passing --unfixable=E501, for example, assuming that would override the value set in the ruff config. The doesn't seem to be the case though, ruff still does not fix the errors.

This does not depend on pre-commit btw, the same can be reproduced by just running ruff from CLI. Essentially, I'm looking for a way to overwrite unfixable, without using --isolated, because there is more config than the minimal example above.

Is there a generally recommended way to do this?

### PR DESCRIPTION
**Pull request by charliermarsh**
# Summary

This PR adds an `--extend-fixable` command-line and configuration file option, and changes the semantics to match those of `--select` (i.e., providing a new `--select` wipes out previous ignores, and so on).

Closes #4289.

### CODE REVIEW

**Comment by MichaReiser** [comment]
My concern with adding `--extend-fixable`, or any other new CLI argument that directly match to a configuration option` is that we ultimately end up with a whole lot of CLI arguments: One to override every option in the configuration. What do you think of adding a `--config [key1=value1,key2=value2,...]` option that allows specifying ANY option in the configuration similar to `rustfmt` or `clippy`?

**Comment by charliermarsh** [comment]
I'm generally open to something like that, though I think in this case, it does make sense to add `--extend-fixable`, since it's an inconsistency in the API:

```
Rule selection:
      --select <RULE_CODE>
          Comma-separated list of rule codes to enable (or ALL, to enable all rules)
      --ignore <RULE_CODE>
          Comma-separated list of rule codes to disable
      --extend-select <RULE_CODE>
          Like --select, but adds additional rule codes on top of the selected ones
      --per-file-ignores <PER_FILE_IGNORES>
          List of mappings from file pattern to code to exclude
      --fixable <RULE_CODE>
          List of rule codes to treat as eligible for autofix. Only applicable when autofix itself is enabled (e.g., via `--fix`)
      --unfixable <RULE_CODE>
          List of rule codes to treat as ineligible for autofix. Only applicable when autofix itself is enabled (e.g., via `--fix`)
```

(Notice that `--extend-select` exists, but not `--extend-fixable`.)

**Review by MichaReiser — APPROVED** [review]

**Comment by MichaReiser** [comment]
> I'm generally open to something like that, though I think in this case, it does make sense to add --extend-fixable, since it's an inconsistency in the API:

What is your suggestion to decide on when we should add new explicit options? Should we also add `extend-ignore`, `extend-per-file-ignores`, and `extend-unfixable`? That's why I think I would prefer to potentially decide on adding support for `--config` (and rename the existing `--config` option to `--config-path`?) because I fear that it will always be possible to reason that some option should be supported because we already support some other option.

**Comment by charliermarsh** [comment]
I think we _should_ add these for all of the rule selection APIs, but not for the rule _configuration_ APIs. That's my general stance right now.

**Pull request merged**
