### PR TITLE
Move violation structs out of `registry.rs`

### PR DESCRIPTION
**Pull request by charliermarsh**

### CODE REVIEW

**Comment by charliermarsh** [comment]
\cc @not-my-profile

**Comment by not-my-profile** [comment]
LGTM!

**Comment by not-my-profile** [comment]
Not related to this PR but I think we should rename `EqCmpop` to `EqCmpOp` ... just because RustPython doesn't follow the convention doesn't mean that we shouldn't.

**Comment by charliermarsh** [comment]
Weirdly CPython does the same thing though: https://github.com/python/cpython/blob/8d69828092f734cd9275459173a0f89bde109659/Grammar/python.gram#L726

**Comment by charliermarsh** [comment]
No objection to me from renaming.

**Pull request merged**
