### PR TITLE
Remove autogenerated `docs/rules/*.md` files

### PR DESCRIPTION
**Pull request by not-my-profile**

### CODE REVIEW

**Comment by JonathanPlasse** [comment]
Should we keep GitHub like in the readme and when generating the docs replace the links by `beta.ruff.rs` links?

**Comment by not-my-profile** [comment]
That doesn't make sense ... when the files are no longer in the repository, we cannot link them to GitHub anymore.

**Comment by JonathanPlasse** [comment]
Ah yes, I only saw the removed lines in the root git ignore and not the new one.
Will it break the links if we add a new doc for a rule but do not make a release immediately?

**Comment by not-my-profile** [comment]
Yes after this PR has been merged the rule links in the README will only work for rules that have been released, since we intentionally now only build the docs on release, see #2717.

While we could have ruff.rs/stable/ and additionally build ruff.rs/unstable/ for every commit ... I don't think this is really worth it. I think instead we can simply remove the rule tables from the README ... which I think would make sense anyway ... the README is way too long. Splitting up the README into multiple `.md` files would also have the benefit that the heading levels in the `.md` file could directly correspond to the heading levels in the website HTML. Currently the website contains `<h1>` tags and then `<h3>` tags ... which is semantically wrong, the latter should be `<h2>` tags. While we could fix this with even more post-processing, I'd rather have us keep things simple.

**Comment by charliermarsh** [comment]
(Had to rebase, hope that's cool.)

**Pull request merged**
