### PR TITLE
Use more precise error ranges for names

### PR DESCRIPTION
**Pull request by harupy**
Improves error ranges for the following rules:

- E741
- PLW0602
- PLE0117

### Current

```
> cargo run -- --select PLW --no-cache --show-source resources/test/fixtures/pylint/global_variable_not_assigned.py --show-source
resources/test/fixtures/pylint/global_variable_not_assigned.py:5:5: PLW0602 Using global for `x` but no assignment is done
  |
5 |     global x
  |     ^^^^^^^^ PLW0602
  |

resources/test/fixtures/pylint/global_variable_not_assigned.py:9:5: PLW0602 Using global for `x` but no assignment is done
  |
9 |     global x
  |     ^^^^^^^^ PLW0602
  |

Found 2 error(s).
```

### Fixed

```
> cargo run -- --select PLW --no-cache resources/test/fixtures/pylint/global_variable_not_assigned.py --show-source
resources/test/fixtures/pylint/global_variable_not_assigned.py:5:12: PLW0602 Using global for `x` but no assignment is done
  |
5 |     global x
  |            ^ PLW0602
  |

resources/test/fixtures/pylint/global_variable_not_assigned.py:9:12: PLW0602 Using global for `x` but no assignment is done
  |
9 |     global x
  |            ^ PLW0602
  |

Found 2 error(s).
```

### CODE REVIEW

**Comment by not-my-profile** [comment]
What's the reasoning behind this range narrowing? The error is about using global, so I think including the `global` keyword in the range actually makes sense ... so I think I prefer the previous ranges.

**Comment by harupy** [comment]
@not-my-profile That makes sense. I'm happy to file a PR to revert the changes for PLW0602 and PLE0117.

**Comment by harupy** [comment]
The range narrowing might make sense in the following case:

```python
def f():
    global x, y, z
    ^^^^^^^^^^^^^^
    x = y = 1
```

vs.

```python
def f():
    global x, y, z
                 ^
    x = y = 1
```

**Comment by not-my-profile** [comment]
Ah ok, yes that does make sense :) I assume ruff doesn't support multi-ranges?

```python
def f():
    global x, y, z
    ^^^^^^       ^
    x = y = 1
```

**Comment by charliermarsh** [comment]
We don’t support multi-ranges right now. It could be useful but I’d need to think on it. It’s tricky because it doesn’t map well to the LSP schema.

**Pull request merged**
