### PR TITLE
Require explicit opt-in for GitHub and Gitlab formats

### PR DESCRIPTION
**Pull request by charliermarsh**

### CODE REVIEW

**Comment by charliermarsh** [comment]
\cc @edgarrmondragon - Does this seem reasonable to you? I think folks will find it surprising that this behavior happens automatically, rather than via explicit configuration or a dedicated action.

**Comment by edgarrmondragon** [comment]
> \cc @edgarrmondragon - Does this seem reasonable to you? I think folks will find it surprising that this behavior happens automatically, rather than via explicit configuration or a dedicated action.

@charliermarsh Yeah, I was following what other tools do (e.g. https://github.com/pytest-dev/pytest-github-actions-annotate-failures) but it makes sense to be explicit.

**Comment by ashb** [comment]
Is there any way I can drive this by an env var?

My setup is I have a `poetry run ruff` in my `.pre-commit.yaml` file. and it would be nice if I could set something like `RUFF_FORMAT=github` or similar to choose the mode. Is this possible? (I couldn't see something like in the docs or a quick skim of the code)

**Comment by charliermarsh** [comment]
It's not supported right now, but I agree that it'd be a useful thing to respect an env var here for that reason. Will add.

**Pull request merged**
