### PR TITLE
[`flake8-simplify`] Add autofix for `contextlib.suppress` (`SIM105`)

### PR DESCRIPTION
**Pull request by leiserfg**

### CODE REVIEW

**Comment by leiserfg** [comment]
Hi @charliermarsh  I saw the new api for edits, I was waiting for something like this to automatically fix sim105. Is there a way to check if the edit works fine (like for checking the diff after playing it in the tests)?

**Comment by charliermarsh** [comment]
@leiserfg - Our fixture tests aren't great for this right now but @MichaReiser is improving them (e.g., we'll be able to see actual diffs rather than JSON representations of the diagnostics as is the case now).

If it were me, I'd just do some manual testing via the CLI on a couple files (e.g., `cargo run -p ruff_cli -- /path/to/file.py --select SIM105 --no-cache --fix`).

**Comment by leiserfg** [comment]
> If it were me, I'd just do some manual testing via the CLI on a couple files

I tried with:
```python
try:
    a = 3
except (Exception1, Exception2, something.Exception3) as e:
    pass


def asdf():
    try:
        a = 3
    except Exception:
        pass
```
and it renders as
```python
import contextlib
with contextlib.suppress(Exception1, Exception2, something.Exception3):
    a = 3


def asdf():
    with contextlib.suppress(Exception):
        a = 3
```

**Comment by leiserfg** [comment]
By the way, should not this rule match also when the body of the handler is `Constant::Ellipsis`?

**Comment by leiserfg** [comment]
The edition will not remove the extra indentation in the case of being in a nested block (as in the function), I can avoid it but it could potentially remove also trailing comments which I think is more dangerous, another run of black will fix it anyways.

**Comment by leiserfg** [comment]
This change takes care of the indentation issue without affecting the comments as comments can't be before the `except`.

**Comment by charliermarsh** [comment]
Nice. I ran this over Bokeh, it worked great:

```diff
diff --git a/docs/bokeh/docserver.py b/docs/bokeh/docserver.py
index eafbdcaf9..d5d7e84c8 100644
--- a/docs/bokeh/docserver.py
+++ b/docs/bokeh/docserver.py
@@ -40,6 +40,7 @@ from tornado.ioloop import IOLoop
 from tornado.wsgi import WSGIContainer
 
 from bokeh.util.tornado import fixup_windows_event_loop_policy
+import contextlib
 
 IOLOOP = None
 HOST = "localhost"
@@ -91,10 +92,9 @@ if __name__ == "__main__":
     browser = threading.Thread(target=open_browser)
     browser.start()
 
-    try:
+    with contextlib.suppress(KeyboardInterrupt):
         input("Press <ENTER> to exit...\n")  # lgtm [py/use-of-input]
-    except KeyboardInterrupt:
-        pass
+
 
     IOLOOP.add_callback(IOLOOP.stop)  # type: ignore
     server.join()
diff --git a/src/bokeh/embed/bundle.py b/src/bokeh/embed/bundle.py
index 1c93fee36..6eebb8da3 100644
--- a/src/bokeh/embed/bundle.py
+++ b/src/bokeh/embed/bundle.py
@@ -49,6 +49,7 @@ from ..settings import settings
 from ..util.compiler import bundle_models
 from ..util.warnings import warn
 from .util import contains_tex_string, is_tex_string
+import contextlib
 
 if TYPE_CHECKING:
     from ..resources import Hashes
@@ -309,10 +310,9 @@ def _bundle_extensions(all_objs: set[Model], resources: Resources) -> list[Exten
         pkg: Pkg | None = None
         if exists(package_path):
             with open(package_path) as io:
-                try:
+                with contextlib.suppress(json.decoder.JSONDecodeError):
                     pkg = json.load(io)
-                except json.decoder.JSONDecodeError:
-                    pass
+
 
         artifact_path: str
         server_url: str
diff --git a/src/bokeh/io/export.py b/src/bokeh/io/export.py
index c72fb332f..6557f7534 100644
--- a/src/bokeh/io/export.py
+++ b/src/bokeh/io/export.py
@@ -23,7 +23,7 @@ log = logging.getLogger(__name__)
 # Standard library imports
 import io
 import os
-from contextlib import contextmanager
+from contextlib import contextmanager, suppress
 from os.path import abspath, expanduser, splitext
 from tempfile import mkstemp
 from typing import (
@@ -514,15 +514,13 @@ class _TempFile:
         if self._closed:
             return
 
-        try:
+        with suppress(OSError):
             os.close(self.fd)
-        except OSError:
-            pass
 
-        try:
+
+        with suppress(OSError):
             os.unlink(self.path)
-        except OSError:
-            pass
+
 
         self._closed = True
 
diff --git a/src/bokeh/models/util/structure.py b/src/bokeh/models/util/structure.py
index 622c23e11..cbfbeef4d 100644
--- a/src/bokeh/models/util/structure.py
+++ b/src/bokeh/models/util/structure.py
@@ -61,6 +61,7 @@ from bokeh.models import (
     TableColumn,
     TapTool,
 )
+import contextlib
 
 if TYPE_CHECKING:
     import pandas as pd
@@ -168,18 +169,15 @@ class _BokehStructureGraph:
             answer1: bool = False
             answer2: bool = False
             answer3: bool = False
-            try:
+            with contextlib.suppress(TypeError, UnsetValueError):
                 answer1 = s in getattr(H, y)
-            except (TypeError, UnsetValueError):
-                pass
-            try:
+
+            with contextlib.suppress(TypeError, UnsetValueError):
                 answer2 = s == getattr(H, y)
-            except (TypeError, UnsetValueError):
-                pass
-            try:
+
+            with contextlib.suppress(AttributeError, ValueError, UnsetValueError):
                 answer3 = s in getattr(H, y).values()
-            except (AttributeError, ValueError, UnsetValueError):
-                pass
+
             return answer1 | answer2 | answer3
 
         K = nx.DiGraph()
diff --git a/tests/support/plugins/file_server.py b/tests/support/plugins/file_server.py
index a0855a678..9f73cd23b 100644
--- a/tests/support/plugins/file_server.py
+++ b/tests/support/plugins/file_server.py
@@ -33,6 +33,7 @@ from urllib.request import URLopener
 
 # External imports
 import pytest
+import contextlib
 
 #-----------------------------------------------------------------------------
 # Globals and constants
@@ -108,11 +109,10 @@ class SimpleWebServer:
     def stop(self) -> None:
         """Stops the server."""
         self.stop_serving = True
-        try:
+        with contextlib.suppress(OSError):
             # This is to force stop the server loop
             URLopener().open(f"http://{self.host}:{self.port}")
-        except OSError:
-            pass
+
         log.info("Shutting down the webserver")
         self.thread.join()
 
diff --git a/tests/unit/bokeh/core/property/test_wrappers__property.py b/tests/unit/bokeh/core/property/test_wrappers__property.py
index cb428dd5f..678301ac2 100644
--- a/tests/unit/bokeh/core/property/test_wrappers__property.py
+++ b/tests/unit/bokeh/core/property/test_wrappers__property.py
@@ -51,6 +51,7 @@ from _util_property import _TestModel
 
 # Module under test
 import bokeh.core.property.wrappers as bcpw # isort:skip
+import contextlib
 
 #-----------------------------------------------------------------------------
 # Setup
@@ -418,15 +419,13 @@ def test_PropertyValueList_mutators(mock_notify: MagicMock) -> None:
     # py2 vs py2. The slice methods are only exist in py2. The tests above
     # exercise all the  cases, this just makes py3 report the non-py3 relevant
     # code as covered.
-    try:
+    with contextlib.suppress(Exception):
         pvl.__setslice__(1,2,3)
-    except Exception:
-        pass
 
-    try:
+
+    with contextlib.suppress(Exception):
         pvl.__delslice__(1,2)
-    except Exception:
-        pass
+
 
 @patch('bokeh.core.property.wrappers.PropertyValueContainer._notify_owners')
 def test_PropertyValueSet_mutators(mock_notify: MagicMock) -> None:
diff --git a/tests/unit/bokeh/embed/test_standalone.py b/tests/unit/bokeh/embed/test_standalone.py
index 0de6cb163..6f749dd47 100644
--- a/tests/unit/bokeh/embed/test_standalone.py
+++ b/tests/unit/bokeh/embed/test_standalone.py
@@ -43,6 +43,7 @@ from bokeh.themes import Theme
 
 # Module under test
 import bokeh.embed.standalone as bes # isort:skip
+import contextlib
 
 #-----------------------------------------------------------------------------
 # Setup
@@ -423,10 +424,9 @@ class Test_json_item:
         # added to a document. Ignoring that since we just want to make sure
         # ODF is called with the expected theme arg.
         theme = Theme(json={})
-        try:
+        with contextlib.suppress(ValueError):
             bes.json_item(test_plot, theme=theme)
-        except ValueError:
-            pass
+
         mock_OFD.assert_called_once_with([test_plot], apply_theme=theme)
 
 
diff --git a/tests/unit/bokeh/embed/test_util__embed.py b/tests/unit/bokeh/embed/test_util__embed.py
index 472bacfda..d43d1bf58 100644
--- a/tests/unit/bokeh/embed/test_util__embed.py
+++ b/tests/unit/bokeh/embed/test_util__embed.py
@@ -38,6 +38,7 @@ from bokeh.util.logconfig import basicConfig
 
 # Module under test
 import bokeh.embed.util as beu # isort:skip
+import contextlib
 
 #-----------------------------------------------------------------------------
 # Setup
@@ -591,10 +592,9 @@ class Test_standalone_docs_json:
         d.add_root(p2)
         # ignore error unpacking None mock result, just checking to see that
         # standalone_docs_json_and_render_items is called as expected
-        try:
+        with contextlib.suppress(ValueError):
             beu.standalone_docs_json([p1, p2])
-        except ValueError:
-            pass
+
         mock_sdjari.assert_called_once_with([p1, p2])
 
     def test_output(self) -> None:
```

**Pull request merged**
