### PR TITLE
refactor: Add Copy implementation to Rule

### PR DESCRIPTION
**Pull request by MichaReiser**
This PR adds a `Copy` implementation to `Rule` because `Rule` is only two bytes large (less than a poiner). 

I don't expect this to improve performance, but it allows us to remove some lifetime annotations.

### CODE REVIEW

**Comment by MichaReiser** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3556** <a href="https://app.graphite.dev/github/pr/charliermarsh/ruff/3556" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/charliermarsh/ruff/3556?utm_source=stack-comment).

**Comment by MichaReiser** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3556** <a href="https://app.graphite.dev/github/pr/charliermarsh/ruff/3556" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/charliermarsh/ruff/3556?utm_source=stack-comment).

**Comment by MichaReiser** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3556** <a href="https://app.graphite.dev/github/pr/charliermarsh/ruff/3556" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/charliermarsh/ruff/3556?utm_source=stack-comment).

**Comment by MichaReiser** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3556** <a href="https://app.graphite.dev/github/pr/charliermarsh/ruff/3556" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/charliermarsh/ruff/3556?utm_source=stack-comment).

**Review by charliermarsh — APPROVED** [review]

**Pull request merged**
