### PR TITLE
[`flake8-tidy-imports`] autofix relative imports

### LINKED ISSUE #2764: Relative import autofix should respect `src`
Thanks for this addition. It seems not to work for me in a src-layout, though. Coming here from the item in the changelog...

```toml
# pyproject.toml
[tool.ruff]
src = ["src", "tests"]
```

```console
$ tree src/
src/
├── purepythonmilter
│   ├── api
│   │   ├── application.py
[...]
│   ├── protocol
│   │   ├── commands.py
│   │   ├── definitions.py
[...]
```

```diff
$ ruff --diff src/purepythonmilter/api/application.py 
--- src/purepythonmilter/api/application.py
+++ src/purepythonmilter/api/application.py
@@ -10,9 +10,9 @@
 from typing import TYPE_CHECKING, Any, ClassVar
 
 import attrs
+from src.protocol import commands, definitions, responses
+from src.server import milterserver
 
-from ..protocol import commands, definitions, responses
-from ..server import milterserver
 from . import interfaces, logger, models
```

I expected `s/src/packagename/` here. Plus, it does not detect it as a first-party module here, I think, as it puts it with the third-party import `attrs`.

I would have expected it to change it into:

```diff
$ ruff --diff src/purepythonmilter/api/application.py 
--- src/purepythonmilter/api/application.py
+++ src/purepythonmilter/api/application.py
@@ -10,9 +10,9 @@
 from typing import TYPE_CHECKING, Any, ClassVar
 
 import attrs

+from purepythonmilter.protocol import commands, definitions, responses
+from purepythonmilter.server import milterserver 
-from ..protocol import commands, definitions, responses
-from ..server import milterserver
 from . import interfaces, logger, models
```

Am I doing something wrong or is this an omission? Thanks!

_Originally posted by @gertvdijk in https://github.com/charliermarsh/ruff/issues/2739#issuecomment-1426792627_

### LINKED ISSUE #2869: Wrong fix for TID252
# File

File path: `app.telegram.handlers.start.py`

 
```tree
app
├── __init__.py
├── __main__.py
└── telegram
    ├── __init__.py
    ├── ...
    ├── filters
    │   ├── __init__.py
    │   └── chat_type.py
    ├── handlers
    │   ├── __init__.py
    │   └── start.py
    └── ...

```

## Before fix

```python
from ..filters import ChatType
```

## Expected fix

```python
from app.telegram.filters import ChatType
```

## Actual fix

```python
from app.filters import ChatType
```

```log
Found 1 error (1 fixed, 0 remaining).
```

### PR DESCRIPTION
**Pull request by sbrugman**
Previous fix was bugged. This one is only fixing when the `module_path` is present, making it far more robust.

Closes #2764 and closes #2869

(Good luck with the Jetbrains Webinar tonight)

### CODE REVIEW

**Comment by charliermarsh** [comment]
> (Good luck with the Jetbrains Webinar tonight)

Thank you, this was nice to read :)

**Comment by not-my-profile** [comment]
The first commit created `resources/test/popmon` as a git submodule? o.O What's up with that?

**Comment by sbrugman** [comment]
Ah, that needs to be removed (thought that I had...). I use it for local testing only

**Comment by gertvdijk** [comment]
It works, thanks all! 🙏🏼

**Pull request merged**
