### PR TITLE
Upgrade RustPython to support parenthesized context managers

### LINKED ISSUE #54: Crash on parenthesized with statement
I tried running ruff on a large project, which resulted in this crash:

```
[2022-08-31][10:33:40][ruff][ERROR] Failed to check repr-with.py: invalid syntax. Got unexpected token 'as' at line 9 column 13
```

It seems like the crash happens on parenthesized context managers introduced in Python 3.10. Minimal reproducible example:

```python
from contextlib import contextmanager

@contextmanager
def ctx():
    yield

with (ctx() as foo):
    ...
```

### LINKED ISSUE #680: E999 syntax error for match statement
ruff throw a syntax error for code like this:
```python3
import sys

value: str = sys.argv[1]

match value:
    case "ruff":
        print("Rough?")
    case "awesome":
        print("Of course is it!")
    case _:
        print("what?")

```

```
$ ruff ruff_and_match.py
Found 1 error(s).
ruff_and_match.py:5:8: E999 SyntaxError: invalid syntax. Got unexpected token 'value'
```

### versions
- Python 3.10.6
- ruff 0.0.108

### config:
```toml
[tool.ruff]
line-length = 100
select=["E", "F", "W", "U", "N", "C", "B", "A", "T", "Q", "
```

(and yes ruff is awesome ;-))

### LINKED ISSUE #847: Parenthesized context managers raise E999
Ruff version: 0.0.132
Ruff configuration: Default

Ruff reports E999 (Syntax Error) for parenthesized context managers [that were introduced in python 3.10](https://docs.python.org/3/whatsnew/3.10.html#parenthesized-context-managers)

This raises E999
```
test.py:2:15: E999 SyntaxError: invalid syntax. Got unexpected token 'as'
```
```py
with (
    open("") as a,
    open("") as b,
):
    pass
```

However it works fine if you use `\` to split line:
```py
with open("") as a, \
    open("") as b:
    pass
```

### PR DESCRIPTION
**Pull request by charliermarsh**
Thanks to @andersk for the fix upstream. We also get much-improved end-locations for functions and classes and other compound statements based on @harupy's work.

Closes #54.
Closes #847.
Closes #680.

### CODE REVIEW

**Comment by squiddy** [comment]
Oh that's great. Thanks @andersk & @harupy. Now I can pitch ruff to my team. It was blocked on this issue.

**Comment by charliermarsh** [comment]
I'm pumped for this!

**Comment by antonagestam** [comment]
This pushed me to try ruff on phantom-types, and I'm very impressed with it! 🚀

https://github.com/antonagestam/phantom-types/pull/259

**Comment by charliermarsh** [comment]
Rock on! Thank you for giving Ruff a try. Looks like a cool project by the way :)

**Comment by 153957** [comment]
This says 'Closes https://github.com/charliermarsh/ruff/issues/680.' But it only fixes the context managers right? Not structural pattern matching which that issues was originally about.

**Comment by andersk** [comment]
Yes, although we still have an open issue for that and we only need one.

- #282

**Comment by charliermarsh** [comment]
(Yes, sorry, my mistake.)

**Pull request merged**
