### PR TITLE
Build ABI3 wheels and expand supported platforms

### PR DESCRIPTION
**Pull request by adriangb**

### CODE REVIEW

**Comment by adriangb** [comment]
Gave this a quick test drive: https://github.com/adriangb/ruff/runs/8084227138?check_suite_focus=true

I do ask that you look at the release gates. I think you intend this to run and release on every tagged commit, even if it's not a commit on `main`.

**Comment by charliermarsh** [comment]
Wait, this is so nice of you? Not only did you go find this repo but you PR'd a huge improvement? Thank you!

For context: I started by copying over the graphlib2 YAML, but at that point, I was still including pyo3 (I later realized this was unnecessary), which was forcing me to build version-specific wheels... so I think some of the individual wheels were failing, because I wasn't building against 3.7? And then I just figured it wasn't worth the painful debugging loop, and gave up on a lot of versions :) This is way better!

**Comment by charliermarsh** [comment]
> I do ask that you look at the release gates. I think you intend this to run and release on every tagged commit, even if it's not a commit on `main`.

For now I only want to upload to PyPI when I create a new release, though I'd be open to creating (and not uploading) the artifacts for every commit.

**Comment by adriangb** [comment]
> I'd be open to creating (and not uploading) the artifacts for every commit

Easy enough: #46. Now you'll have artifacts on GitHub for every commit but only publish to PyPi on tags. I guess one could download and install those wheels specifically if they wanted to. Shame you can't link to them directly (so you can't point pip at them).

Sorry about that rogue lint step.

**Pull request merged**
