### PR TITLE
Show settings path in `--show-settings` output

### PR DESCRIPTION
**Pull request by dhruvmanila**
## Summary

Create a new struct called `PyprojectConfig` which holds all the `pyproject.toml` configuration related information. This includes the discovery strategy used (`Fixed` or `Hierarchical`), the settings itself and absolute path to the `pyproject.toml` file.

Using `PyprojectConfig::new` will try to resolve the given config path to absolute.

## Test Plan

***Project structure:***

```
.
├── pyproject.toml
├── src
│   └── ...
└── test
    ├── foo
    │   └── __init__.py
    └── pyproject.toml
```

<details><summary><b>Using `--isolated` (no config path):</b></summary>
<p>

```console
$ ~/contributing/astral/ruff/target/debug/ruff check --show-settings --isolated . | head -n8  
Resolved settings for: "/Users/dhruv/playground/python/ruff-play/src/B031.py"
Settings {
    rules: RuleTable {
        enabled: {
            MixedSpacesAndTabs,
            MultipleImportsOnOneLine,
            ModuleImportNotAtTopOfFile,
            LineTooLong,
```

</p>
</details> 

<details><summary><b>Using <code>--config pyproject.toml</code></b></summary>
<p>

```console
$ ~/contributing/astral/ruff/target/debug/ruff check --show-settings --config=pyproject.toml . | head -n8
Resolved settings for: "/Users/dhruv/playground/python/ruff-play/src/B031.py"
Settings path: "/Users/dhruv/playground/python/ruff-play/pyproject.toml"
Settings {
    rules: RuleTable {
        enabled: {
            UnnecessaryCallAroundSorted,
            UnnecessaryCollectionCall,
            UnnecessaryComprehension,
```

</p>
</details> 

<details><summary><b>Using <code>--config ../pyproject.toml</code></b></summary>
<p>

```console
$ ~/contributing/astral/ruff/target/debug/ruff check --show-settings --config=../pyproject.toml . | head -n8 
Resolved settings for: "/Users/dhruv/playground/python/ruff-play/test/foo/__init__.py"
Settings path: "/Users/dhruv/playground/python/ruff-play/pyproject.toml"
Settings {
    rules: RuleTable {
        enabled: {
            UnnecessaryCallAroundSorted,
            UnnecessaryCollectionCall,
            UnnecessaryComprehension,
```

</p>
</details> 

<details><summary><b>Using hierarchical strategy to find config file</b></summary>
<p>

```console
$ ~/contributing/astral/ruff/target/debug/ruff check --show-settings . | head -n8          
Resolved settings for: "/Users/dhruv/playground/python/ruff-play/src/B031.py"
Settings path: "/Users/dhruv/playground/python/ruff-play/pyproject.toml"
Settings {
    rules: RuleTable {
        enabled: {
            UnnecessaryCallAroundSorted,
            UnnecessaryCollectionCall,
            UnnecessaryComprehension,
```

</p>
</details> 

<details><summary><b>No config file (commented out <code>[tool.ruff]</code> section)</b></summary>
<p>

```console
$ ~/contributing/astral/ruff/target/debug/ruff check --show-settings . | head -n8  
Resolved settings for: "/Users/dhruv/playground/python/ruff-play/src/B031.py"
Settings {
    rules: RuleTable {
        enabled: {
            MixedSpacesAndTabs,
            MultipleImportsOnOneLine,
            ModuleImportNotAtTopOfFile,
            LineTooLong,
```

</p>
</details> 

resolves: #3202

### CODE REVIEW

**Review by MichaReiser — APPROVED** [review]
Overall looks good to me. I personally would prefer to store the path on the `PyprojectDiscovery` rather than the `AllSettings` because the `path` isn't a setting. But that likely results in a larger change because it requires re-modelling `PyprojectDiscovery`:

```rust
struct PyprojectDiscovery {
	strategy: PyprojectDiscoveryStrategy,
	root_settings: AllSettings,
	root_settings_path: Option<PathBuf>
}

#[derive(Debug, Copy, Clone, Eq, PartialEq)]
enum PyprojectDiscoveryStrategy {
	Fixed,
	Hierarchical
}
```

What's your take on this?

Could you add a test plan to the PR summary showing the new output?

**Comment by dhruvmanila** [comment]
> What's your take on this?

This is a much better idea. At first I thought to add it as an additional element to the tuple itself but I think a struct is a better option for the long term.

> Could you add a test plan to the PR summary showing the new output?

Yes, will add it.

---

I'll make both the changes in the evening.

**Comment by dhruvmanila** [comment]
I've updated the code and PR description :)

I'm getting `error: Broken pipe (os error 32)` when I'm piping it to the `head` command. Is it a bug or some problem in my shell?

**Review by MichaReiser — APPROVED** [review]

**Comment by MichaReiser** [comment]
> I'm getting `error: Broken pipe (os error 32)` when I'm piping it to the `head` command. Is it a bug or some problem in my shell?

I experienced this in the past too when using `less` but haven't spent any time investigating why this is happening.

**Comment by dhruvmanila** [comment]
I think this is related: https://github.com/rust-lang/rust/issues/46016

**Pull request merged**
