### PR TITLE
Add proc-macro to derive `CheckCodePrefix`

### PR DESCRIPTION
**Pull request by messense**
IMO a derive macro is a natural way to generate new code, and it reduces the chance of merge conflicts.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Yeah this makes a lot of sense, thank you. My main critique of macros like this is that they hurt the IDE experience, since (e.g.) `CheckCodePrefix` will no longer autocomplete in the editor... But this does seem more natural, and it also solves some of the bootstrapping problems that we have today, whereby we can't reference check code prefixes before generating them, etc.

**Comment by charliermarsh** [comment]
(Nice work.)

**Comment by not-my-profile** [comment]
>My main critique of macros like this is that they hurt the IDE experience, since (e.g.) CheckCodePrefix will no longer autocomplete in the editor...

Autocompletion works fine for me using rust-analyzer, which has [`rust-analyzer.procMacro.enable`](https://rust-analyzer.github.io/manual.html#rust-analyzer.procMacro.enable) enabled by default. Are you using another language server for rust? I highly recommend rust-analyzer.

**Comment by messense** [comment]
I think intellij-rust also works fine with derive macros now: https://github.com/intellij-rust/intellij-rust/issues/6908

**Comment by messense** [comment]
That's odd, it works for me, maybe you need to enable the `Expand macros` option

image

image

**Comment by charliermarsh** [comment]
I think I had to enable some more stuff in "Experimental features" -- looks like it's working now! Amazing! Thanks both!

Screen Shot 2023-01-06 at 7 36 01 AM

**Pull request merged**
