### PR TITLE
Enable skipping based on .gitignore

### LINKED ISSUE #174: Consider auto-excluding files matched by gitignore files
Patterns would need to be read from:
- `.gitignore` file in the same directory as the path, or in any parent directory (the latter allows tools to put a `.gitignore` file with `*` in the directory they create to auto-exclude themselves)
- patterns read from `$GIT_DIR/info/exclude` (allows user-specific patterns for a specific repository)
- patterns read from the file specified by Git's configuration variable `core.excludesFile` (allows global user-specific patterns, I personally use this one)

Reference: https://git-scm.com/docs/gitignore

This might come at a performance cost but it definitely would be a useful feature.

### PR DESCRIPTION
**Pull request by charliermarsh**
This works but it's kind of slow -- it increases the benchmark time from ~300ms to ~420ms which feels like a lot for a nice-to-have feature, so I'd want to make this opt-in.

Alternatively (or in addition): the .gitignore changes infrequently, so I could probably cache the exclusion checks?

Resolves #174.

### CODE REVIEW

**Comment by charliermarsh** [comment]
(This still needs a CLI argument before it can be merged.)

**Comment by charliermarsh** [comment]
\cc @jack1142

**Comment by jack1142** [comment]
I pip installed it from the PR's head branch and it doesn't seem to work.

Configuration:
- `$PROJECT_ROOT/.gitignore`
```
.folder/
should_not_be_here4.py
```
- `$PROJECT_ROOT/.git/info/exclude`:
```
should_not_be_here2.py
```
- `~/.gitignore_global` (I have `core.excludesFile` set to that file):
```
should_not_be_here3.py
```
File tree:
```
- .folder/
+-- should_not_be_here1.py
- .git/
+-- files and folders
- .ruff_cache/
+-- files and folders
- .venv/
+-- files and folders
- .gitignore
- should_be_here.py
- should_not_be_here2.py
- should_not_be_here3.py
- should_not_be_here4.py
```

The output of `ruff .`:
```
❯ ruff . 
Failed to load pyproject.toml: No such file or directory (os error 2)
Falling back to default configuration...
Found 5 error(s).
./.folder/should_not_be_here1.py:2:5: F841 Local variable `x` is assigned to but never used
./should_be_here.py:2:5: F841 Local variable `x` is assigned to but never used
./should_not_be_here2.py:2:5: F841 Local variable `x` is assigned to but never used
./should_not_be_here3.py:2:5: F841 Local variable `x` is assigned to but never used
./should_not_be_here4.py:2:5: F841 Local variable `x` is assigned to but never used
```

`should_not_be_here*` files are the ones that should be ignored while `should_be_here*` shouldn't.

**Comment by jack1142** [comment]
Update: now that wheels got uploaded by CI, I tried installing from the built wheel instead but that didn't change the result.

**Comment by jack1142** [comment]
> (This still needs a CLI argument before it can be merged.)

Okay, I just realized that this only means there's no CLI option but the pyproject.toml setting is there :smile: 

But surprisingly, adding this doesn't change the result (aside from ruff no longer complaining about missing pyproject.toml):
```
[tool.ruff]
skip-gitignore = true
```

**Comment by jack1142** [comment]
I made #203 which could be a potential cause for me having trouble with getting anything to match here as well.

**Comment by charliermarsh** [comment]
The only files I'd expect to be excluded here with current implementation are `should_not_be_here1.py` and `should_not_be_here4.py` -- this is just looking at the local gitignore, and not at the global ignore or `.git/info/exclude`.

**Comment by charliermarsh** [comment]
I had the code setup to log-but-not-actually-ignore files so as to avoid affecting the benchmark while testing. Can you try again? If you run with `--verbose`, it should tell you which files are excluded (and why).

**Comment by jack1142** [comment]
Actually one more case is adding `.gitignore` in subfolders, e.g.
`another_directory/.gitignore`:
```
*
```
should cause entire `another_directory` to be ignored (which is taken advantage of by various tools).

That reminds me I need to make an issue for adding `.gitignore` with `*` contents to the `.ruff_cache` folder as that's actually what a lot of tools do (mypy, pytest, virtualenv to name a few) :)

**Comment by charliermarsh** [comment]
Cool yeah, adding the `.gitignore` is straightforward :)

**Comment by charliermarsh** [comment]
I'm probably going to de-prioritize supporting auto-exclusion based on `.gitignore`, at least until I fix + stablize the `skip` globbing behavior, since (once that works) you can always just use skips to achieve the same effect (less conveniently).

**Comment by jack1142** [comment]
My personal use case is ignoring directories specific to me (especially the virtual environment folders I create where I don't particularly follow conventions as much, as the conventions don't really allow me to have virtual environments for multiple Python version organized neatly) which is why I suggested a more general request for supporting git ignores since it's more likely to be supported by multiple tools.

But personally, I wouldn't mind much just having a user-specific file for configuring excludes but that has the whole other issue of whether the project config should override or extend such configuration (personally I want it to extend *but* it doesn't work well for other settings in a more general case of user configuration rather than user excludes configuration) so I don't think it would work as well as this could.

Either way, de-prioritizing it makes sense to me, it's not particularly critical while ruff is in early adoption phase since it's somewhat unlikely that I would personally work on a project that uses ruff and is not maintained by me (it could happen since you've already reached some big project maintainers but I'm guessing I won't personally encounter an external project I want to contribute to that uses ruff quite yet) and I can put excludes specific to me in configuration for projects *I* maintain :smile:

**Pull request closed without merging**
