### PR TITLE
Subcommand followups

### PR DESCRIPTION
**Pull request by not-my-profile**
(See the commit messages for the reasoning.)

### CODE REVIEW

**Comment by charliermarsh** [comment]
Are there any analogies we can draw to other tools, to help inform the user-facing API for the CLI?

E.g., `rustup` has `rustup toolchain list`. Should we have `ruff rule list` instead of just `ruff rule`?

**Comment by not-my-profile** [comment]
Yes `git branch` lists git branches. `ruff rule list` would be ambiguous in case there's a rule named `list`.

**Comment by charliermarsh** [comment]
Appreciate it. I don't plan to release tonight either way :)

**Comment by not-my-profile** [comment]
I just want to note that if we want to change `explain` to `rule` (I personally think it's a good idea) we should do that before releasing the subcommand refactor so that the release notes in `BREAKING_CHANGES.md` stay up to date.

To clarify my commit message: At some point in the future we may have:

`ruff config banned-api` to explain the `banned-api` config option

`ruff rule banned-api` to explain the `banned-api` rule

... if we only had `explain` it would have to report both, which would be confusing. And we also would have to introduce separate subcommands for listing linters, rules, config settings ... I think having a setup where one subcommand lists everything by default and shows an individual item with another argument makes more sense.

**Comment by charliermarsh** [comment]
@not-my-profile - anything you think is missing / preventing us from cutting a release, now that this is merged?

**Comment by not-my-profile** [comment]
No, I don't see anything else blocking a new release :)

**Pull request merged**
