### PR TITLE
Add Pylint rule `C0208` (`use-sequence-for-iteration`) as `PLC0208` (`iteration-over-set`)

### PR DESCRIPTION
**Pull request by tjkuson**
## Summary

Implement the Pylint [C0208 rule](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/use-sequence-for-iteration.html) that checks for `set` iterators. Related to https://github.com/charliermarsh/ruff/issues/970. Includes documentation.

Currently, it checks for iterating over in-place `set` but not `set` names. For example, this triggers the rule:

```python
for item in {1, 2, 3}:
    ...
```

But this does not:

```python
items = {1, 2, 3}
for item in items:
    ...
```

I am curious whether this should be the case. On the one hand, using a `set` via a name incurs the same performance impact as using a `set` literal. However, it is unclear if using a named `set` invites the same recommendation to replace it with a sequence (there could be a conversion cost, and a `set` might be more efficient elsewhere). *This is also how Pylint currently implements the rule.*

## Test Plan

Added test fixtures.

### CODE REVIEW

**Comment by tjkuson** [comment]
I think the rule is ready for review. To my knowledge, it is at par with Pylint C0208.

**Review by MichaReiser — APPROVED** [review]

**Comment by andersk** [comment]
Pylint does *not* flag `for i in set(a)`, and I don’t think we should either. The [point of this rule](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/use-sequence-for-iteration.html) is for efficiency:

- `for i in {1, 2, 3}` → `for i in [1, 2, 3]` is more efficient, but
- `for i in set(a)` → `for i in a` is incorrect (`set` deduplicates), and
- `for i in set(a)` → `for i in list(set(a))` is less efficient (we still iterate over the `set` to build the `list`).

**Comment by charliermarsh** [comment]
Ah interesting. By that logic, we'd want to omit set-comprehensions too?

**Comment by andersk** [comment]
Yes (and Pylint allows them too).

**Comment by charliermarsh** [comment]
Yeah, this makes sense. I'll get this change in before cutting the next release (or feel free to PR if you'd like).

**Pull request merged**
