### PR TITLE
Do not Change Quotation Style for `SIM118` Autofix

### PR DESCRIPTION
**Pull request by saadmk11**
closes https://github.com/charliermarsh/ruff/issues/1523

### CODE REVIEW

**Comment by squiddy** [comment]
I have a feeling we would need to look into other plugins then as well. There are many cases where we just string manipulate the code, and not use the source code generator.

I was initially confused as to why this is a bug, but apparently we want to fix code style issues of code we're not even touching? All the previous implementation was doing is to strip off `.keys()`.

Wondering where we draw the line, e.g.:

```python
for x in data['something']:
     print('hello')
```

`x` is unused here, so we rename it to `_x`. Do we also fix the quotes of the iterable? What about the loop body?

**Comment by saadmk11** [comment]
This actually makes it so that the linter does not automatically change the quotation style of the code it is updating as described in the linked issue. Sorry if the PR title was a bit miss leading. 🙂

**Comment by squiddy** [comment]
> This actually makes it so that the linter does not automatically change the quotation style of the code it is updating as described in the linked issue. Sorry if the PR title was a bit misleading. 🙂

Oh sorry, now I see it. The `to_string` on the node introduces the double quotes probably. Thank you.

Perhaps we can add a test case for that.

**Comment by charliermarsh** [comment]
Thanks!

**Comment by charliermarsh** [comment]
My general philosophy on the quoting stuff right now: we're not obligated to "fix" incorrect quotes, but we shouldn't make them "worse". So if a snippet uses single quotes, but the rest of the file uses double quotes, and we introduce a fix that changes the snippet but doesn't correct the quotes -- that's fine.

On the other hand: if a snippet uses single quotes, and the whole file uses single quotes, and we change it to double quotes -- that's wrong.

**Pull request merged**
