### PR TITLE
Remove `assertNotContains`

### PR DESCRIPTION
**Pull request by harupy**
`unittest.TestCase` doens't have a method named `assertNotContains`.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Any idea why this was included initially?

**Comment by harupy** [comment]
I originally came from https://github.com/charliermarsh/ruff/pull/1506/files#diff-63acef36182d791074bf61c44d3b9715f8783e11f6314869597ea761cdd48d0aR82. cc @eddiebergman

**Comment by harupy** [comment]
To confirm, the following code prints out False
```
import unittest

print("assertNotContains" in dir(unittest.TestCase))
```

**Comment by andersk** [comment]
Might be a Django thing? https://docs.djangoproject.com/en/4.1/topics/testing/tools/#django.test.SimpleTestCase.assertNotContains

**Comment by harupy** [comment]
@andersk Thanks for the comment!

**Comment by harupy** [comment]
If `assertNotContains` was Django's assertNotContains, would it make sense to emit PT009?

**Comment by charliermarsh** [comment]
Alright I did some digging here. It looks like `flake8-pytest-style` ported this from `flake8-pytest`. `flake8-pytest` originally included Django's `SimpleTestCase` methods, then removed them [here](https://github.com/vikingco/flake8-pytest/commit/8f44e4f474bcf9f2979a2684cec750d19a17504a), but left `assertNotContains`. I'm guessing that was an oversight? So, yes, we should remove it.

**Comment by harupy** [comment]
@charliermarsh Thanks for the investigation. Agreed.

**Comment by charliermarsh** [comment]
It's maybe worth auditing the methods here. I think we're missing [`assertCountEqual`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertCountEqual)? Although maybe that's it.

**Comment by harupy** [comment]
@charliermarsh Agreed, filed #1736

**Pull request merged**
