### PR TITLE
Implement SIM118 (key in dict) of flake8-simplify

### PR DESCRIPTION
**Pull request by squiddy**
Refs: #998

### CODE REVIEW

**Comment by charliermarsh** [comment]
Awesome, and thanks for handling all the new-plugin boilerplate. I'd love to automate some of that, I have a hacky Bash script but...

**Comment by squiddy** [comment]
> I'd love to automate some of that, I have a hacky Bash script but...

Haha, I was thinking the same. Mind sharing your bash script? I'm in the process of cleaning up some existing code to align all of it better.

**Comment by charliermarsh** [comment]
Hahah I mean, I'll share it, but it's embarrassing and incomplete! It really just creates a few files and directories, and then added the sequence of comments to `checks.rs` in a way that could be cleaned up by `cargo fmt`. But it's probably not even worth looking at sadly.

```sh
set -euxo pipefail

NAME=$1

mkdir -p src/$1
mkdir -p resources/test/fixtures/$1
touch src/$1/mod.rs

sed -i "" "s/mod flake8_print;/mod flake8_print; mod flake8_return;/g" src/lib.rs
sed -i "" "s|// flake8-print|// flake8-return\n// flake8-print|g" src/checks.rs
```

**Comment by squiddy** [comment]
Thanks, I'll try to put something together.

**Pull request merged**
