### PR TITLE
Update contributing guide for adding new lint rules

### PR DESCRIPTION
**Pull request by messense**
Noticed when doing #1621

### CODE REVIEW

**Comment by charliermarsh** [comment]
Oh gosh, sorry, I literally _just_ did this like two seconds ago. Thank you 🙏

**Comment by messense** [comment]
Great! BTW it'd be nice to have some docs about adding auto-fixes.

**Comment by charliermarsh** [comment]
Totally agree...

**Comment by charliermarsh** [comment]
https://github.com/charliermarsh/ruff/issues/1625

**Pull request closed without merging**
