### PR TITLE
[`pylint`]: bad-string-format-type

### PR DESCRIPTION
**Pull request by colin99d**
ref: #970

### CODE REVIEW

**Comment by colin99d** [comment]
Do we need to keep the restriction that this only works of the statement is one line. I got this from copying code in UP031, and I am not sure if it still applies here.

**Comment by colin99d** [comment]
Also, do we have a way of knowing the type of a variable? For example, pylint can throw a warning here:
```
WORD = "abc"
"%d" % WORD
```

But we cannot, because I am not sure how to tell pylint that the type of WORD is string.

**Comment by not-my-profile** [comment]
This PR again created `src/registry.rs`.

**Comment by spaceone** [comment]
There are a lot of false positives introduced, I started a collection here: https://github.com/charliermarsh/ruff/issues/2724

**Pull request merged**
