### PR TITLE
[`tryceratops`]: Too Many Try Statements

### PR DESCRIPTION
**Pull request by colin99d**
Merge after #3109 because this closes: #2056

### CODE REVIEW

**Comment by charliermarsh** [comment]
I'm conflicted on this one. I see the intent of what the rule is trying to do, but even in the [example](https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TC101.md), I'm not certain the fixed version is better:

```py
def main_function():
    try:
        receipt_note = receipt_service.create(order_id)
        broker.emit_receipt_note(receipt_note)
    except ReceiptNoteCreationFailed:
        logger.exception("log")
        raise
    except NoteEmissionFailed:
        logger.exception("another log")
        raise
```

Since it's now unclear which statement is expected to throw which exception. I ran this over Zulip too and it hit some cases where it wouldn't make sense to refactor in this way (e.g., a function with a `for` loop that handles an exception in body, followed by another exception handler way down after the loop). In general, I actually think handling exceptions in the narrowest scope possible is _good_.

What do you think?

**Comment by colin99d** [comment]
I think the bigger issue is if we have two separate blocks catching a ValueError.

**Comment by colin99d** [comment]
Im gonna go ahead and close this.

**Comment by ericbuehl** [comment]
I have a strong preference for the opposite of what [TRY101](https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TRY101.md) promotes -- specifically addressed by [Pylint W0717](https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/too-many-try-statements.html) (unfortunately using the same name as this proposed rule 🙃).  Is there any ongoing work to implement Pylint W0717 in ruff?  If not I may take a stab at it

**Comment by Pierre-Sassoulas** [comment]
Seems like we could rename the pylint check to ``too-many-statements-inside-try`` to differentiate the two.

**Pull request closed without merging**
