### PR TITLE
Merge convert-loop-to-any & convert-loop-to-all to reimplemented-builtin

### PR DESCRIPTION
**Pull request by not-my-profile**
Part of #2714.

### CODE REVIEW

**Comment by charliermarsh** [comment]
I'm cool with merging these, but should we consider a more refined name? Like `reimplemented-loop-builtin`? `reimplemented-builtin` feels a bit too broad vis-a-vis the actual scope of the rule.

**Comment by not-my-profile** [comment]
There aren't that many builtin functions. If you look at the [list of builtin functions](https://docs.python.org/3/library/functions.html#built-in-funcs), I think it would be quite feasible that the lint would also check for abs, enumerate, filter, len, map, max, min, round, sum and zip.

**Comment by charliermarsh** [comment]
Mmm ok, that's fair!

I may merge this after the next release (tomorrow, probably), but I can own rebasing etc. as needed.

**Comment by not-my-profile** [comment]
Opened #2942 to track the implementation of further reimplemented builtin checks.

**Comment by charliermarsh** [comment]
@not-my-profile - This is technically a breaking change, right? Since if a user had `# noqa: SIM111`, the suppressed error would now show up as `SIM110`. Or am I misunderstanding?

**Comment by not-my-profile** [comment]
I redirected SIM111 to SIM110, so I think ignoring either of these codes should work ... at least that's what I intended.

**Comment by charliermarsh** [comment]
Oh sorry, yes, I think you're probably right.

**Pull request merged**
