### PR TITLE
Preserve comments when sorting imports

### LINKED ISSUE #675: Import sorting deletes comments
(This is a known limitation mentioned in https://github.com/charliermarsh/ruff/issues/465#issuecomment-1311075618, but might as well be tracked as an issue.)

`ruff --select=I --fix` incorrectly transforms

```python
# preserved
import os  # deleted

# deleted
import third_party  # deleted
```

into

```python
# preserved
import os

import third_party
```

### PR DESCRIPTION
**Pull request by charliermarsh**
It's tough to come up with a strategy that does the "right" thing in all cases (in part, because it's hard to even define the "right" output in every case), but this PR preserves _all_ comments, is stable across re-runs, and tries to do sensible things when merging across imports.

Resolves #675.

### CODE REVIEW

**Comment by charliermarsh** [comment]
I'll add a few examples here tomorrow.

**Comment by andersk** [comment]
There’s a slight Black incompatibility—Black requires this newline:

```python
import math
import os

# a comment
import pathlib
import sys
```

while ruff deletes it:

```python
import math
import os
# a comment
import pathlib
import sys
```

**Comment by andersk** [comment]
Comments seem to be unexpectedly counted toward the length of the following line in some cases, causing the following import to wrap early:

```python
import a
# ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
from b import c
```

→

```python
import a
# ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
from b import (
    c,
)
```

**Comment by charliermarsh** [comment]
Woo thanks for trying! I noticed the second issue when running on Zulip :)

It's late here so will fix these both tomorrow (then hopefully merge).

**Comment by andersk** [comment]
Multi-line comments are unexpectedly sorted and deduplicated:

```python
import io
# Old MacDonald had a farm,
# EIEIO
# And on his farm he had a cow,
# EIEIO
# With a moo-moo here and a moo-moo there
# Here a moo, there a moo, everywhere moo-moo
# Old MacDonald had a farm,
# EIEIO
from errno import EIO
```

→

```python
import io
# And on his farm he had a cow,
# EIEIO
# Here a moo, there a moo, everywhere moo-moo
# Old MacDonald had a farm,
# With a moo-moo here and a moo-moo there
from errno import (
    EIO,
)
```

**Pull request merged**
