### PR TITLE
docs(README): add missing `flake8-simplify`

### PR DESCRIPTION
**Pull request by mkniewallner**
Noticed that `flake8-simplify` is mentioned [here](https://github.com/charliermarsh/ruff#flake8-simplify-sim), but not in the list of tools that `ruff` can replace.

I based the total number of rules on what's listed in https://github.com/MartinThoma/flake8-simplify#rules (without the "legacyfix" and "removed" ones) and included the experimental rules (`SIM9`), but if you prefer not to include the experimental ones, it totals to 30 rules.

### CODE REVIEW

**Comment by charliermarsh** [comment]
I think I omitted it initially because we'd only done one rule so far, but this is also fine :)

**Comment by charliermarsh** [comment]
Somehow I got 33 rules when I created the table [here](https://github.com/charliermarsh/ruff/issues/998) -- is the discrepancy obvious to you? Is that table missing some, or the other way around?

**Comment by mkniewallner** [comment]
> I think I omitted it initially because we'd only done one rule so far, but this is also fine :)

Ha, I was wondering if it was intentional or not, but since there are other plugins listed with only 1 rule (`autoflake` and `flake8-tidy-imports`, although they have way less total rules), I wasn't sure.

> Somehow I got 33 rules when I created the table [here](https://github.com/charliermarsh/ruff/issues/998) -- is the discrepancy obvious to you? Is that table missing some, or the other way around?

Differences I can see:
- `SIM104` is in the list, and I didn't count it as it is listed as a "legacyfix"
- `SIM224` is in the list, but it's a placeholder for an experimental rule
- `SIM124` is in the list, but it's a placeholder for an experimental rule

**Comment by mkniewallner** [comment]
The list also doesn't include experimental rules under `SIM9` (although it's probably intended), so without the 3 extra rules, it totals to 30 (and 37 if we count the experimental ones).

**Comment by charliermarsh** [comment]
Ok cool -- let's go with your list, those explanations make sense! I'll merge and edit the issue.

**Pull request merged**
