### PR TITLE
Make D410/D411 autofixes mutually exclusive

### LINKED ISSUE #3827: Docstring autofixer adds too much whitespace
My function docstring looks like this, and is missing whitespace between the sections "Parameters" and "Examples"

```python
def pow(self, exponent: int | float | Series | Expr) -> Self:
    """
    Raise expression to the power of the given exponent.

    Parameters
    ----------
    exponent
        ...
    Examples
    --------
    >>> df = pl.DataFrame({"foo": [1, 2, 3, 4]})

    """
    ...
```

After autofixing, two blank lines are inserted. Only a single blank line would be sufficient:

```python
def pow(self, exponent: int | float | Series | Expr) -> Self:
    """
    Raise expression to the power of the given exponent.

    Parameters
    ----------
    exponent
        ...


    Examples
    --------
    >>> df = pl.DataFrame({"foo": [1, 2, 3, 4]})

    """
    ...
```

The reason seems to be that `D410` (missing blank line after section) and `D411` (missing blank line before section) are applied at the same time.

This is on the latest ruff version.

### PR DESCRIPTION
**Pull request by evanrittenhouse**
This should close #3827.

I tested by having a `test.py` file (repro'd from the issue):
```
def pow(self, exponent: int | float):
    """
    Raise expression to the power of the given exponent.

    Parameters
    ----------
    exponent
        ...
    Examples
    --------
    >>> df = pl.DataFrame({"foo": [1, 2, 3, 4]})

    """
    ...

```

I then ran `cargo run -p ruff_cli -- check test.py --fix --select D410 --select D411` and ensured that only one new line was created between `...` and `Examples`. As a sanity check, I also reset the file and performed the same test with no whitespace after `>>> df...`.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Can we think of any way to fix this by ensuring that the generated fixes are identical? That way, we'll deduplicate them when we go to apply the generated fixes.

The issue with the approach in here is that we won't generate a fix at all for one of the two violations, IIUC, which means that in the VS Code extension and elsewhere, we won't show a code action for users to automatically fix it.

**Comment by charliermarsh** [comment]
I think the goal should be that the two rules independently produce an identical fix in this case, and that we return both diagnostics with their respective fixes, and defer to the fix-applied to deduplicate. Is that possible to achieve?

**Comment by evanrittenhouse** [comment]
Should be! I basically changed `NoBlankLineAfterSection` to insert the newline at the first character of the next line (where `NoBlankLineBeforeSection` does) to avoid conflicts. I'll have to rebase against `main` to fix conflicts with #3931, I think.

**Comment by evanrittenhouse** [comment]
@charliermarsh you're too quick, was going to finish it out after work today!

**Comment by charliermarsh** [comment]
Haha no worries. Trying to see if I can remove the iterator clone, but I have a few meetings so I'll return to this later or you can beat me to it. Will merge tonight.

**Comment by evanrittenhouse** [comment]
Clean solution with the `peek()` @charliermarsh

**Pull request merged**
