### PR TITLE
define_simple_violation

### PR DESCRIPTION
**Pull request by akx**
This PR defines a pair of new macros, `define_simple_violation!`, `define_simple_autofix_validation!` that define an unit struct and derive the `Violation`/`AlwaysAutofixableViolation` traits.

Since this hasn't been really discussed or anything, just a pattern that repeated throughout the Great Violation Migration, I'm totally fine with this being nixed, e.g. on the grounds of avoiding [Tim Toady](https://en.wikipedia.org/wiki/There%27s_more_than_one_way_to_do_it). (Even if the PR looks like it could've been a lot of work, it honestly wasn't – the majority of the half-hour here was spent tweaking the regexp I used to find the current simple-enough violations 😁 )

### CODE REVIEW

**Comment by charliermarsh** [comment]
That procedural macro API looks very nice...

**Comment by akx** [comment]
I'll see what I can do with proc macros..!

**Comment by akx** [comment]
Ah, I'm not sure I have the bandwidth to look at proc macros right now, so I'll close this to keep it from littering the PR list :)

**Comment by charliermarsh** [comment]
All good, thanks for following up :)

**Pull request closed without merging**
