### PR TITLE
Avoid erroneous Q002 error message for single-quote docstrings

### LINKED ISSUE #1775: Incorrect label for docstring error
Screenshot 2023-01-10 at 9 04 07 PM

I believe the wording on this warning is incorrect. It is fixed by switching to triple quotes. However, it says you need double quotes.

### PR DESCRIPTION
**Pull request by colin99d**
Fixes #1775. Before implementing your solution I thought of a slightly simpler one. However, it will let this function pass:
```
def double_inside_single(a):
    'Double inside "single "'
```
If we want function to pass, my implementation works. But if we do not, then I can go with how you suggested I implemented this (I left how I would begin to handle it commented out). The bottom of the flake8-quotes documentation seems to suggest that this should pass:
https://pypi.org/project/flake8-quotes/

### CODE REVIEW

**Comment by colin99d** [comment]
I went to check how flake8-quotes handles this, and it looks like out of the box they throw an error on what we are trying to fix.
'''
def double_inside_single(a):
    "This is a test"
'''
Results in:
resources/test/fixtures/flake8_quotes/docstring_doubles_function.py:31:5: Q002 Single quote docstring found but double quotes preferred

So I will leave it up to you to decide on the quotes inside quotes edge case I found above. After that I will add the test fix and we can merge this thing!

**Comment by charliermarsh** [comment]
Okay I'm struggling to understand the originating plugin's logic but here's my guess.

If you have `Double` enabled, these should be ok:

```py
def f():
    """Docstring"""

def f():
    "Docstring"

def f():
    """Doc'string"""

def f():
    "Doc'string"

def f():
    'Doc"string'

def f():
    '''Doc"string'''
```

And these should error:

```py
def f():
    '''Docstring'''

def f():
    'Docstring'
```

If you have `Single` enabled, the reverse should be true. So all of these should be ok:

```py
def f():
    '''Docstring'''

def f():
    'Docstring'

def f():
    '''Doc"string'''

def f():
    'Doc"string'

def f():
    "Doc'string"

def f():
    """Doc'string"""
```

**Comment by charliermarsh** [comment]
(I think we probably have the same bug as the library, because I copied the logic exactly.)

**Comment by colin99d** [comment]
At first I made a complicated function:
fn contains_good_docstring(quote: &Quote, raw_str: &str) -> bool {
    match quote {
        Quote::Single => raw_str.contains("'''") || raw_str.contains("'"),
        Quote::Double => raw_str.contains("\"\"\"") || raw_str.contains('"'),
    }
}
But now im realizing we simplify it to this:
At first I made a complicated function:
fn contains_good_docstring(quote: &Quote, raw_str: &str) -> bool {
    match quote {
        Quote::Single => raw_str.contains("'"),
        Quote::Double => raw_str.contains('"'),
    }
}

And with this we can pretty much just take it back to the original function. But with a single character instead of triples.

**Comment by colin99d** [comment]
Changes in! This should work as "if single there needs to be a single quote SOMEWHERE, and if double there needs to be a double quote SOMEWHERE".

**Comment by charliermarsh** [comment]
@colin99d - If you're interested in a follow-up...

If we _are_ using a triple quote, I don't _think_ we should allow you to invert the quote style. That is, if you're preferring `"`, and you do this:

```py
def f():
  '''This has a quote " in it.'''
```

I think, perhaps, that should be considered a violation, since you can just do this:

```py
def f():
  """This has a quote " in it."""
```

So the flexibility we added here, IMO, should only apply when using single-quoted docstrings.

**Comment by colin99d** [comment]
> @colin99d - If you're interested in a follow-up...
> 
> If we _are_ using a triple quote, I don't _think_ we should allow you to invert the quote style. That is, if you're preferring `"`, and you do this:
> 
> ```python
> def f():
>   '''This has a quote " in it.'''
> ```
> 
> I think, perhaps, that should be considered a violation, since you can just do this:
> 
> ```python
> def f():
>   """This has a quote " in it."""
> ```
> 
> So the flexibility we added here, IMO, should only apply when using single-quoted docstrings.

Makes sense to me! Thanks for the explanation.

**Comment by charliermarsh** [comment]
Another way of looking at it is... what would Black convert?

Black changes this to double quotes:

```py
def f():
    '''Some "docstring.'''
```

But not this:

```py
x = 'here is a quote " inside'
```

**Comment by colin99d** [comment]
> Another way of looking at it is... what would Black convert?
> 
> Black changes this to double quotes:
> 
> ```python
> def f():
>     '''Some "docstring.'''
> ```
> 
> But not this:
> 
> ```python
> x = 'here is a quote " inside'
> ```

From now on I will just let what would black do answer formatting ambiguity questions I have.

**Comment by charliermarsh** [comment]
In our case, though, we also the opposite, if the user has `Quote::Single` set :)

**Pull request merged**
