### PR TITLE
ci(check_ecosystem): add PyPa/build

### PR DESCRIPTION
**Pull request by henryiii**
Adding PyPA/build.

### CODE REVIEW

**Comment by charliermarsh** [comment]
@henryiii - Any ideas on how to resolve the above?

**Comment by henryiii** [comment]
It’s reading the pyproject.toml’s in test, I guess? Those need to be ignored. There are examples of broken toml files. Running it normally doesn’t have this issue.

**Comment by charliermarsh** [comment]
I do get it when running locally:

```
❯ ruff .
error: TOML parse error at line 2, column 19
  |
2 | requires = ['bad' 'syntax']
  |                   ^
invalid array
expected `]
```

Does the typical invocation run over `src` specifically, or something like that?

**Comment by henryiii** [comment]
Typical invocation is via pre-commit, https://github.com/pypa/build/blob/e496fe6342f0e4729b69d0ea93eef529f27875a6/.pre-commit-config.yaml#L41. It probably passes all Python files explicitly. Maybe it doesn’t pick up toml files in that case?

**Comment by henryiii** [comment]
Will it ignore them if I exclude tests/**/pyproject.toml?

**Comment by charliermarsh** [comment]
I'll take a look, we need to exclude the entire directory so that it doesn't try to find the `pyproject.toml` file for any of the surfaced files.

**Comment by charliermarsh** [comment]
Omitting `test` entirely works, but that's not what you want. Omitting _just_ that directory doesn't seem to work. I'll take a look, we might need to fix something in Ruff.

**Comment by henryiii** [comment]
Yeah, I tried omitting the directory and the file. Don't want to omit `test`. :)

**Comment by charliermarsh** [comment]
Haha yeah I figured :)

We have to load configuration files as we traverse, because the set of exclusions can change as we go deeper into the filesystem and find the relevant configuration files for each directory. So I'm guessing we're loading that config too eagerly somewhere despite the exclusion.

**Comment by henryiii** [comment]
I expect the exclusion still needs to be added to build. I can do that in a bit.

**Comment by charliermarsh** [comment]
🤦 Right right, sorry. A _release_ isn't necessary, but the exclusion does need to be added.

**Comment by henryiii** [comment]
Why is it passing, actually?

**Comment by charliermarsh** [comment]
The ecosystem check doesn't fail CI, but the error _is_ being reported in the comment, I think:

Screen Shot 2023-03-18 at 4 08 32 PM

**Pull request merged**
