### PR TITLE
Establish rule naming convention & disallow certain rule names

### PR DESCRIPTION
**Pull request by not-my-profile**
Part of #1773.

I would have also disallowed rule names starting with use-* but that is currently blocked by #2714.

### CODE REVIEW

**Comment by charliermarsh** [comment]
This is great! Thank you @not-my-profile.

**Comment by charliermarsh** [comment]
Can I squash this to get rid of the intermediary commits (like `cargo dev generate-all`)? Or do you want to rebase them out?

**Comment by not-my-profile** [comment]
Rebased the  `cargo dev generate` commit into the previous commits.

If you'd resolve #2714, I could also rename the use-* rules ... or we could do that in a followup PR, whatever you prefer.

**Comment by charliermarsh** [comment]
Let's do it in a follow-up, I'll try to resolve #2714 today.

**Pull request merged**
