### PR TITLE
add: MkDocs GitHub Pages

### PR DESCRIPTION
**Pull request by juftin**
## Summary

Addresses: https://github.com/charliermarsh/ruff/issues/1398

I saw you mentioned mdBook in the above issue - MkDocs is a strong markdown based static site that could work in the meantime before nicer solutions get built with mdBooks. 

This PR adds a [mkdocs](https://www.mkdocs.org/) site with the [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) theme. I think it does a good job of making the `README` easier to digest - and will work nicely when/if the docs are split up too. 

Once implemented you're ready to host a free site at https://charliermarsh.github.io/ruff

image

Let me know what you think, and if you're interested - I'm happy to help customize and improve the docs as well. Here's the site temporarily hosted from my fork: https://juftin.com/ruff/

### CI/CD

`mkdocs` GitHub Actions Workflow copies `README.md` to `docs/index.md`, commits any changes to the `main` branch. Finally it uses `mkdocs` to publish the static HTML site to the `gh-pages` branch.

## Running Locally

```shell
pipx install mkdocs
pipx inject mkdocs mkdocs-material
mkdocs serve --livereload
```

### GH Pages

You may need to activate GitHub Pages to source from the `gh-pages` branch here: https://github.com/charliermarsh/ruff/settings/pages

image

### Personal Access Token

You'll need to add a Personal Access Token as a GitHub secret for this to commit changes to the main branch since it's protected - I'm referencing the `PERSONAL_ACCESS_TOKEN` secret name.

### CODE REVIEW

**Comment by messense** [comment]
I‘d recommend build and host on Netlify instead, gh-pages will make `git clone` size grow much larger in the long run.

**Comment by Jackenmen** [comment]
GitHub pages can be deployed using GH Actions without having to keep a dedicated branch:
https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow

**Comment by messense** [comment]
> GitHub pages can be deployed using GH Actions without having to keep a dedicated branch:
> https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow

Great!

**Comment by charliermarsh** [comment]
Thanks so much for this! It's so cool to see.

Let me think a bit on (1) MkDocs vs. mdBook, and (2) deployment / hosting, prior to merging this. It's hard to roll back a public site / artifact, so I want to ensure I've given all the tradeoffs sufficient thought.

On (2): we already host the playground at [https://play.ruff.rs/](https://play.ruff.rs/) on Cloudflare Pages, so I'll likely tweak this setup to use Pages too for simplicity with DNS and such. But that's easy for me to change.

**Comment by juftin** [comment]
Sounds great - the nice thing about MkDocs is that it was extremely low effort to set up. If you decide to go with it, great. If not, no worries. Excited to see the future of docs @ ruff!

**Comment by charliermarsh** [comment]
I had to make some follow-up changes to this, but it just merged as #2287. I would've pushed here, but didn't have edit rights -- sorry to create a separate PR, but hopefully you're credited as the author in Git since I preserved you in the co-commit. Really appreciate you pushing us here!

**Pull request closed without merging**
