### PR TITLE
Update CI to test `python -m ruff` on release

### PR DESCRIPTION
**Pull request by madkinsz**
To prevent future regressions like https://github.com/charliermarsh/ruff/issues/4394

### CODE REVIEW

**Comment by charliermarsh** [comment]
Thank you, great idea.

**Comment by charliermarsh** [comment]
Hopefully CI actually fails here? :)

**Comment by madkinsz** [comment]
@charliermarsh I only updated the `release` workflow. I think we'll need to add a new CI workflow for testing Python package builds if you want coverage per pull request (which is a great idea too).

**Comment by charliermarsh** [comment]
Oh right right. Thanks.

**Comment by konstin** [comment]
thanks!

**Pull request merged**
