### PR TITLE
Respect --force-exclude for files passed via stdin

### LINKED ISSUE #1339: Exclude option ignored when directly calling dir/file
MWE:
```toml
[tool.ruff]
exclude = [ "blah" ]
```
`blah/test.py`:
```python
import os
```
Running ruff on `.` returns nothing, but running `ruff ./blah` or `ruff ./blah/test.py` will return the diagnostics (F401) even if blah was excluded. Is this intentional?

### PR DESCRIPTION
**Pull request by charliermarsh**
Resolves #1339.

### CODE REVIEW

**Comment by charliermarsh** [comment]
It turns out that it's very, very hard to use the `ignore` crate to answer the question, "Is a given path ignored?", because it doesn't _seem_ to expose the underlying matchers, only the directory walkers. This creates a few problems. I'll just leave this comment here for posterity as I roll back some of the code:

```
// Step 2: Is the file ignored via a gitignore?
// Note that we can't enforce this behavior for non-existent files, which _could_ come up when
// you pass a file via `--stdin-filename`, and _could_ be considered incorrect. For example,
// if `subdir` is listed in the `gitignore`, and you pass `subdir/non_existent_file.py`, then
// right now, we _wouldn't_ mark that theoretical file as ignored. If the `ignore` crate had
// a public matcher API, we could support that, but right now, we _have_ to look at the
// filesystem to reverse-engineer the gitignore match.
```

```
// TODO(charlie): This isn't right either, because the _parent_ could be the thing that's
// ignored via the `.gitignore`.
```

**Comment by charliermarsh** [comment]
Resolves #1339.

**Comment by jhossbach** [comment]
Seems like I was too slow. Also closes #1343

**Comment by charliermarsh** [comment]
Sadly this doesn't respect gitignore rules in those cases (I tried to get this to work for a while, but I don't think it's reliable without changes to the `ignore` crate), but otherwise seems to work.

**Pull request merged**
