### PR TITLE
Remove --max-complexity from the CLI

### PR DESCRIPTION
**Pull request by charliermarsh**

### CODE REVIEW

**Comment by not-my-profile** [comment]
Should this be documented in `BREAKING_CHANGES.md`?

**Comment by charliermarsh** [comment]
Yeah, it should. I'll add it.

**Comment by cclauss** [comment]
Not a fan of this choice...  It is quite helpful when building up a new config to be able to test on the CLI before writing the complete config into `pyproject.toml`.

**Comment by not-my-profile** [comment]
I think the change makes sense ... `mccabe.max-complexity` isn't more important than any other rule-specific settings and we certainly don't want to introduce a dedicated command-line option for each of our rule-specific settings.

What we could do is introduce a more generic mechanism such as `--config <KEY>=<VALUE>`.

**Comment by cclauss** [comment]
The error message is misleading because (at least on my Mac) I cannot figure out how to make the `-- --x` escaping to work.

% `ruff --max-complexity=10 .`
```
error: unexpected argument '--max-complexity' found

  note: to pass '--max-complexity' as a value, use '-- --max-complexity'
```

% `ruff --mccabe.max-complexity=10 .`
```
error: unexpected argument '--mccabe.max-complexity' found

  note: to pass '--max-complexity' as a value, use '-- --mccabe.max-complexity'
```

**Pull request merged**
