### PR TITLE
[`pyupgrade`] Remove `keep-runtime-typing` setting

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This was implemented "by accident" before realizing that it's exactly equivalent to turning off two of our rules. (Pyupgrade doesn't have a generic mechanism for turning off individual rules, and so has dedicated flags for them.)

### CODE REVIEW

**Comment by layday** [comment]
I don't think the two mechanisms are exactly equivalent.  The benefit of having a stand-alone setting for it is that the rules will take effect immediately upon bumping the minimum supported Python version, whereas now the user will have to remember to un-exclude the rules they've been forced to exclude for runtime typing compatibility, and the burden of tracking compatibility per Python version will have fallen on them.

**Comment by charliermarsh** [comment]
@layday - I understand that perspective, but these rules already take the minimum compatible version into account (and/or the required presence of `from __future__ import annotations`), so I don't believe users should have to consider their own minimum supported version at all when enabling or disabling them, or toggling the `keep-runtime-typing ` settings. There was more discussion of this here (https://github.com/charliermarsh/ruff/issues/3174), long ago -- but, e.g., the only reason to turn these rules off or set `keep-runtime-typing = true` would be if you had some application behavior that depended on the availability of runtime typing, and in that case, it seems like changing the Python version would be irrelevant to whether that decision changed.

As implemented in Ruff, this setting was exactly equivalent to enabling and disabling these rules. But I'm happy to continue discussing or reconsider if you have an example of where this would cause problems.

**Comment by layday** [comment]
> [...] would be if you had some application behavior that depended on the availability of runtime typing, and in that case, it seems like changing the Python version would be irrelevant to whether that decision changed.

Ah, but the assumption is that the application is able to handle these new typing constructs at runtime, the only limitation being the lowest Python version that it supports, i.e. that evaluating stringified annotations does not raise.

> As implemented in Ruff, this setting was exactly equivalent to enabling and disabling these rules.

To clarify, bumping `target-version` to 3.10 would not have enabled either of these rules?

**Comment by charliermarsh** [comment]
> To clarify, bumping target-version to 3.10 would not have enabled either of these rules?

That's correct. It _used_ to only affect the pre-3.10 branch, but I changed it in #2449. I may have misunderstood the motivation for the flag, and it's possible that our enforcement of it was incorrect, though I still don't fully understand why it exists. It seems like the example of a case in which users want to use this flag is on pre-3.9 code like:

```py
from __future__ import annotations
import pydantic

class User(pydantic.BaseModel):
    first_name: str | None = None
    last_name: str | None = None
```

But in this case, why is `__future__` annotations enabled? Is it not unsafe to use `__future__` annotations at all if you're relying on runtime typing in this way?

**Comment by JacobHayes** [comment]
One might also use `from __future__ import annotations` to make recursive or cyclic type hints nicer, eg:
```python
from __future__ import annotations

import pydantic

class User(pydantic.BaseModel):
    friends: list[User]
```
([here's a non-contrived example](https://github.com/artigraph/artigraph/blob/golden/src/arti/fingerprints/__init__.py#L48))

---

This may be fairly minor, but if there are future syntax incompatible typing PEPs introduced other than PEP 585 and PEP 604, one other difference is that users (as opposed to ruff) will need to be responsible for updating their configs when making ruff updates in order to keep runtime typing.

**Pull request merged**
