### PR TITLE
Re-style the Ruff playground

### PR DESCRIPTION
**Pull request by charliermarsh**

### CODE REVIEW

**Comment by squiddy** [comment]
Looks great! :tada: 

Have you considered adding the JSON schema to the settings editor? Example: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults

**Comment by charliermarsh** [comment]
@squiddy - Hah! I actually just did that before seeing your comment!

**Comment by charliermarsh** [comment]
You'll notice I chose to just use a JSON editor for settings. I think it's a little simpler, lets us leverage the schema, and avoids having to build a lot of custom form UI.

**Comment by charliermarsh** [comment]
I should probably change the default settings to come from Wasm. Then we wouldn't need the TS codegen step, I think...

**Comment by squiddy** [comment]
> You'll notice I chose to just use a JSON editor for settings. I think it's a little simpler, lets us leverage the schema, and avoids having to build a lot of custom form UI.

Yeah, much more sensible for the target audience as well.

As for the default options coming from wasm, I think getting rid of that separate TS file is also one step towards (easier) version selection. One less file next to the wam to worry about.

**Comment by charliermarsh** [comment]
Yeah. The last thing for version selection would be the JSON schema. It probably doesn’t make sense to include that in the WASM, but we could just upload a versioned copy on every release.

**Comment by charliermarsh** [comment]
I have a few more TODOs to improve the playground, but they’re purely additive.

**Pull request merged**
