### PR TITLE
Enable prefix-based check code selection

### LINKED ISSUE #325: Support selecting and ignoring groups of codes
Flake8 supports options like

* `flake8 --ignore=E` (ignore all `E???` rules)
* `flake8 --select=E5` (enable all `E5??` rules)
* `flake8 --select=E,E50 --ignore=E5,E501` (select all `E???` rules, except `E5??` which are ignored, except `E50?` which are selected, except `E501` which is ignored)

It might be nice to support this or something similar.

### PR DESCRIPTION
**Pull request by charliermarsh**
Resolves #325.

### CODE REVIEW

**Comment by charliermarsh** [comment]
\cc @andersk

**Comment by andersk** [comment]
In Flake8, the most specific prefix wins, whether it’s a select or an ignore. In this implementation, ignores always win, so you can’t override a broad `--ignore=E5` with a specific `--select=E50`.

**Comment by charliermarsh** [comment]
Ah ok. We can do that. I assume that ties break in favor of `--ignore`? Such that `--select A100 --ignore A100` ignores A100?

**Comment by andersk** [comment]
Yeah, `--select` wins if it’s longer, `--ignore` wins if it’s longer or equal.

https://github.com/PyCQA/flake8/blob/7dfe99616fc2f07c0017df2ba5fa884158f3ea8a/src/flake8/style_guide.py#L171-L177

**Pull request merged**
