### PR TITLE
Remove remove-six-compat (UP016)

### PR DESCRIPTION
**Pull request by charliermarsh**
See discussion in #2049.

### CODE REVIEW

**Comment by charliermarsh** [comment]
In which PR?

**Comment by charliermarsh** [comment]
(Let's rebase it, I'd like this to be a separate PR.)

**Comment by spaceone** [comment]
:-( it was and will be useful for me in the future (we can drop Py2 next year)

**Comment by charliermarsh** [comment]
@spaceone - Sorry about that :( I recommend using `pyupgrade` for this check. I felt like the implementation in Ruff was complex and under-tested since it's a rarely-run rule.

**Pull request merged**
