### PR TITLE
Check for Unsupported Files and Display Errors and Warnings

### PR DESCRIPTION
**Pull request by saadmk11**
closes https://github.com/charliermarsh/ruff/issues/1473

**Reference:**

> - (Optional) If we don't find _any_ files, show a warning.
> - If we're passed a non `.py` or `.pyi` file, raise an error for that file (but process any valid files).

_Originally posted by @charliermarsh in https://github.com/charliermarsh/ruff/issues/1473#issuecomment-1368082842_

### CODE REVIEW

**Comment by charliermarsh** [comment]
Thank you! I decided to make the "unsupported file type" thing a hard error. I may regret it, we'll see!

**Comment by andersk** [comment]
We have many Python scripts that are marked executable with a shebang line but without a `.py` extension. I think this should be reverted.

**Comment by charliermarsh** [comment]
Do you want / expect those to be linted? If so, how have you linted them in the past, given that we only check `.py` and `.pyi` files?

**Comment by charliermarsh** [comment]
We can change this to just attempt to lint them, which would raise a syntax error for any non-Python files that are passed directly.

**Comment by andersk** [comment]
We linted all files passed directly on the command line, regardless of extension, until pretty recently (I’m checking where this changed).

**Comment by charliermarsh** [comment]
Okay, I'm happy to revert to that behavior.

**Comment by charliermarsh** [comment]
(I guess my question was: are you passing those directly on the command line?)

**Comment by andersk** [comment]
Yes, we have a wrapper script that finds all the Python files in the Git repository via extensions and shebang lines, and passes them directly on the command line.

**Comment by charliermarsh** [comment]
Ok, I can fix this later tonight. Or feel free to send a PR of course. Sorry for the trouble.

**Comment by andersk** [comment]
`git bisect` shows this changed in #1241.

(The problem isn’t urgent for Zulip, since Zulip uses a pinned version of Ruff.)

**Comment by charliermarsh** [comment]
Tracking here: #1541

**Pull request merged**
