### PR TITLE
ignore if using infinite iterators in `B905`

### PR DESCRIPTION
**Pull request by kyoto7250**
## Summary

```python
# https://github.com/PyCQA/flake8-bugbear/issues/378
from itertools import count


for _, _ in zip("abc", count()):
    pass
```

`ruff` raises B905 warning.

```bash
$ ruff --select B905 x.py
x.py:5:13: B905 `zip()` without an explicit `strict=` parameter
Found 1 error.
```

but, if we add `strict=True`, this is invalid code.
```bash
ValueError: zip() argument 2 is longer than argument 1
```

## Test Plan

We don't need to warn if `zip` has itertools.count, cycle, repeat. 

I also added test cases.

## Reference
- https://docs.python.org/3/library/itertools.html
- https://github.com/PyCQA/flake8-bugbear/issues/378
- https://github.com/PyCQA/flake8-bugbear/pull/388

This PR was created to have the same behavior as `flake8_bugbear`, but if an infinite iterator is used and `strict=True` is given, it may be better to issue a separate dedicated warning.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Thanks! It looks like the bugbear PR also checks whether the `repeat` call has `times=None` (or is omitted): https://github.com/PyCQA/flake8-bugbear/pull/388/files#diff-21e991c5e10f0aca96647b43b4d0968e75c52cc2bceaacf0794f50ded872e49bR1184. Do you think that's worth adding? I don't feel strongly.

**Comment by kyoto7250** [comment]
I missed this conditional branch.

The purpose is to match the behavior with bugbear, so I'm thinking about adding it 👍

**Comment by charliermarsh** [comment]
Gonna adjust this real quick so I can include it in the upcoming release.

**Comment by kyoto7250** [comment]
I Understood, thanks for your work!

**Pull request merged**
