### PR TITLE
Add autofix for W605 [InvalidEscapeSequence]

### PR DESCRIPTION
**Pull request by Sawbez**
I added the autofix, updated the README, and updated the insta tests.

### CODE REVIEW

**Comment by andersk** [comment]
@cclauss Docstrings are not exempt from the normal Python syntax rules about string literals. If you want to include a Windows path in a docstring, you still need to escape the backslashes ( `"""… C:\\documents\\README.md …"""`) or write the docstring as raw (`r"""… C:\documents\README.txt …"""`). Otherwise not just Ruff but also Python itself will warn (if you have warnings enabled), and this may become a syntax error in the future. Also pydoc and other documentation generators will interpret the valid `\r` and `\n` escape sequences in your docstring as written and render something like

```
        Windows files of interest:
        * C:\documents\README.md
        * D: eadme\README.txt
        * Z:
    et_disk\README.rst
```

So ignoring W605 is not a good plan.

**Comment by cclauss** [comment]
The leading `r` on this is also acceptable.

r"""
Windows files of interest:
* C:\documents\README.md
* D:\readme\README.txt
* Z:\net_disk\README.rst
"""  # noqa: W605

**Comment by andersk** [comment]
It’s acceptable to Ruff too. Just because the autofixer wants to fix it one way doesn’t mean you’re not allowed to fix it a different way!

The main reason the autofixer has to go with `\\` is that it can’t read your mind and know that you intend to remove the effects of the valid escape sequences that might also be present, such as your `\r` and `\n`. It aims to never change the meaning of your code.

**Comment by cclauss** [comment]
Please reread the first few paragraphs of https://docs.python.org/3/library/re.html

**Comment by andersk** [comment]
What I’m saying is that if the autofixer were to change `"""C:\documents, D:\readme"""` to `r"""C:\documents, D:\readme"""` as you suggest, that would be a parsed as a *different string*. It would change the meaning of your code. It might happen to be a good change in this case, but Ruff can’t know that, and either way it doesn’t want to automatically change the meaning of your code.

**Comment by cclauss** [comment]
Nice example.  I understand now.  Thanks.

**Pull request merged**
