### PR TITLE
Ignore `collapsible-if` violations for `if False:` and `if True:`

### LINKED ISSUE #2919: SIM223 autofix makes no sense?
`SIM223` fixes:

```diff
-               if False and self._requestid2response_queue:  # FIXME: check for open requests
+               if False:  # FIXME: check for open requests
```

this is temporarily deactivated code.
`if False: …` makes even less sense.
The whole if-block could be removed but I doubt this is good for some autofixer.

### PR DESCRIPTION
**Pull request by JonathanPlasse**
- Close #2919

Instead of using this to disable code
```python
if False and self._requestid2response_queue:
	do_something()
```
Use this
```python
if False:
    if self._requestid2response_queue:
        do_something()
```
It will still flag the rule SIM102 but will not auto-fix.

### CODE REVIEW

**Comment by charliermarsh** [comment]
I think the intent of #2919 was, perhaps, to avoid fixing these at all, since the author was suggesting that the use of `if False and X` was to temporarily deactivate the block while leaving the intended condition (`X`). We might consider just closing that issue, I don't know that we can really do much apart from removing that autofix entirely. If the code is intended to be temporarily disabled, then we should recommend:

```py
if False:
  if condition:
    ...
```

**Comment by JonathanPlasse** [comment]
https://github.com/apache/airflow/blob/f7d5b165fcb8983bd82a852dcc5088b4b7d26a91/airflow/providers/databricks/operators/databricks.py#L73-L76
> ```python
> if "error" in run_output:
>     notebook_error = run_output["error"]
> else:
>     notebook_error = run_state.state_message
> ```
https://github.com/zulip/zulip/blob/0bcf03ea64ebc8ad6e621935933196e45dd26e1c/zerver/worker/queue_processors.py#L458-L461
> ```python
> if "email_language" in data:
>     email_language = data["email_language"]
> else:
>     email_language = referrer.realm.default_language

Both if fixed could cause behavior change as attribute access can have side effects.

**Comment by charliermarsh** [comment]
Which rule are we talking about, for clarity?

**Comment by JonathanPlasse** [comment]
I changed the scope of the issue, as it is bigger than #2919.
The function `contain_effect` did not consider that attribute access could have side effects.

> Which rule are we talking about, for clarity?

It concerns all rules that use `contain_effect`.

**Comment by JonathanPlasse** [comment]
This concerns these rules:
- `UselessExpression`
- `CompareWithTuple`
- `ExprAndNotExpr`
- `ExprOrTrue`
- `ExprAndFalse`
- `IfElseBlockInsteadOfDictLookup`
- `IfElseBlockInsteadOfDictGet`
- `UnusedVariable`

**Comment by JonathanPlasse** [comment]
Should I add tests for each rule concerned?

**Comment by charliermarsh** [comment]
Na that's not necessary. I'm just thinking about the tradeoffs here. It's true that it could be unsafe to change these, but it also hinders our ability to fix a lot of useful and valid cases, since the vast majority of attribute accesses are _not_ effectful.

**Comment by charliermarsh** [comment]
(Separately: for `ExprOrTrue` and `ExprAndFalse`, we should only abort if the effect-ful expression comes _after_ the short-circuiting condition. E.g., `False and foo()` can be removed, since `foo()` will never execute regardless; but `foo() and False` can't be removed.)

**Comment by JonathanPlasse** [comment]
> (Separately: for `ExprOrTrue` and `ExprAndFalse`, we should only abort if the effect-ful expression comes _after_ the short-circuiting condition. E.g., `False and foo()` can be removed, since `foo()` will never execute regardless; but `foo() and False` can't be removed.)

I will make a following PR to fix this.

> Na that's not necessary. I'm just thinking about the tradeoffs here. It's true that it could be unsafe to change these, but it also hinders our ability to fix a lot of useful and valid cases, since the vast majority of attribute accesses are not effectful.

I reverted the changes, as you said it will cause too many false negatives for the added auto-fix safety.

**Pull request merged**
