### PR TITLE
[`tryceratops`]: Check to continue

### PR DESCRIPTION
**Pull request by colin99d**
#2056

### CODE REVIEW

**Comment by colin99d** [comment]
@charliermarsh I am almost done, I just need to know what to make this rule one. It looks like [the original rule](https://github.com/guilatrova/tryceratops/blob/main/src/tryceratops/analyzers/call.py#L140) was hooked into the Module AST item, but I dont see that option in ruff.

**Comment by charliermarsh** [comment]
@colin99d - So I haven't looked at the rule deeply, but `Module` is just the top level of the AST: the module body, a list of statements. I guess this rule wants to do a full AST traversal, but we typically have `ast.rs` do the traversal and call out to the rules at the appropriate time.

**Comment by colin99d** [comment]
Ok I got it figured out! Just need to make one small change with the line number I report, and this will be good to go.

**Comment by charliermarsh** [comment]
I'm really very very genuinely sorry to do this again, but... I don't think we should merge this rule. It's marked as experimental in `tryceratops`, and while I try to avoid injecting too much of my own opinion into which rules are accepted, I feel like this rule is sort of misguided in that handling expected failure modes explicitly can be clearer and _more_ readable than hiding them under exception handling.

I know I asked for help closing out the `tryceratops` ticket, so I feel extra bad closing this PR. I didn't do a good job of validating that we _actually_ wanted each of the remaining rules -- I tend not to look at them closely until I see a PR, but I will try to do better going forward.

**Comment by colin99d** [comment]
@charliermarsh, I was actually going to start the description of this rule with "I am morally against this rule, but here it is anyway". I definitly agree that this rule makes code worse.

**Comment by charliermarsh** [comment]
Lol

**Pull request closed without merging**
