### PR TITLE
refactor: RuleOrigin, RuleCodePrefix and Rule::origin

### PR DESCRIPTION
**Pull request by not-my-profile**
I am about to implement the many to many mapping between codes and rules and would like to rename these two enums in advance because the names don't really make much sense anymore.

As a followup I will drop the all the partial prefixes from `RuleCodePrefix`, see https://github.com/charliermarsh/ruff/issues/1773#issuecomment-1378203413, i.e. you will only be able to select/ignore: one specific rule (e.g. `F401`, all rules from a linter (e.g. `F`) or all rules (`ALL`). While this is not strictly necessary to implement the many to many mapping (or human friendly linter names) it does enable the many to many mapping implementation to be prefix agnostic which I think is a really nice feature since ruff prefixes currently often diverge from the upstream prefixes and by having a prefix-agnostic mapping we can support both the existing ruff rule codes as well as the large legacy code bases that want to switch to ruff without having to rewrite all of their `noqa` directives.

### CODE REVIEW

**Comment by not-my-profile** [comment]
I think I could come up with a clever workaround to still support such partial prefix matches while still avoiding the disadvantageous hardcoding of prefixes.

**Comment by charliermarsh** [comment]
Yeah I just don’t want to break compatibility without a clear and thoughtful strategy. Sounds like we’re on the same page. (An edition or versioned configuration would help with this, in theory? Though it’ll also come automatically if users move to the kebab-case rule names.)

I’ll do a brief compilation of some of the common cases here via GitHub Code Search. For what it’s worth, I think the partial prefix match is mostly used for disabling subsets of docstring rules.

**Comment by charliermarsh** [comment]
Just read through this -- looks reasonable to me. (But now needs a rebase. Will merge whenever it's updated.)

**Comment by not-my-profile** [comment]
Rebased :)

**Pull request merged**
