### PR TITLE
Support linting input from stdin

### LINKED ISSUE #249: Support for stdin?
Hey there, thanks for working on this project. I'm curious if you'd be open to support stdin, similar to how flake8 does it? (i.e. support `-` as the file name and a flag to identify the filename for error messages -- `--stdin-display-name`)

I can send a PR if that's acceptable!

### PR DESCRIPTION
**Pull request by harupy**
Resolve #249

Test:

https://user-images.githubusercontent.com/17039389/194880579-70cb418c-142a-4bfe-b331-1e1a51e23e68.mov

### CODE REVIEW

**Comment by charliermarsh** [comment]
Wooo!

**Comment by charliermarsh** [comment]
@harupy - Is this ready for review?

**Comment by harupy** [comment]
@charliermarsh Yes!

**Comment by harupy** [comment]
@charliermarsh Do you think we need tests?

```rust
#[cfg(test)]
mod tests {
    use std::str;

    use anyhow::Result;
    use assert_cmd::Command;

    #[test]
    fn test_stdin_success() -> Result<()> {
        let mut cmd = Command::cargo_bin("ruff")?;
        cmd.args(&["-"]).write_stdin("").assert().success();
        Ok(())
    }

    #[test]
    fn test_stdin_error() -> Result<()> {
        let mut cmd = Command::cargo_bin("ruff")?;
        let output = cmd
            .args(&["-"])
            .write_stdin("import os\n")
            .assert()
            .failure();
        assert!(str::from_utf8(&output.get_output().stdout)?.contains("-:1:1: F401"));
        Ok(())
    }

    #[test]
    fn test_stdin_error_filename() -> Result<()> {
        let mut cmd = Command::cargo_bin("ruff")?;
        let output = cmd
            .args(&["-", "--stdin-filename", "F401.py"])
            .write_stdin("import os\n")
            .assert()
            .failure();
        assert!(str::from_utf8(&output.get_output().stdout)?.contains("F401.py:1:1: F401"));
        Ok(())
    }

    #[test]
    fn test_stdin_autofix() -> Result<()> {
        let mut cmd = Command::cargo_bin("ruff")?;
        let output = cmd
            .args(&["-", "--fix"])
            .write_stdin("import os\n")
            .assert()
            .success();
        assert!(str::from_utf8(&output.get_output().stdout)?.contains("Found 0 error(s) (1 fixed)"));
        Ok(())
    }
}
```

**Comment by harupy** [comment]
@charliermarsh I'm reading https://doc.rust-lang.org/cargo/reference/cargo-targets.html#integration-tests which states:


> Binary targets are automatically built if there is an integration test. This allows an integration test to execute the binary to exercise and test its behavior. The CARGO_BIN_EXE_<name> [environment variable](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates) is set when the integration test is built so that it can use the [env macro](https://doc.rust-lang.org/std/macro.env.html) to locate the executable.

`assert_cmd` uses `CARGO_BIN_EXE_<name>`:

https://github.com/assert-rs/assert_cmd/blob/295731db56a3887dbc1cfe6601436b42e4646a2e/src/cargo.rs#L204

**Comment by charliermarsh** [comment]
This looks great! Going to make one small API tweak to `fixer.rs` then merge.

**Comment by charliermarsh** [comment]
@harupy - I ended up disabling autofix, since it's a little confusing to say that errors are "fixed" when we're not actually writing _back_ in any way. Let me know if you disagree though!

**Comment by harupy** [comment]
@charliermarsh Makes sense!

**Comment by charliermarsh** [comment]
Thank you for this, great change.

**Comment by fsouza** [comment]
@charliermarsh one way that `--autofix` could work is by writing the fixed code to stdout. What do you think?

This would enable editor integration (like usually the editor sends the source to stdin and read it back from stdout)

**Comment by charliermarsh** [comment]
Yeah that's doable! Is there any example of another tool that does this? Wondering about things like: Would we only write the fixed code to stdout when `--fix` is passed in? Would we write back the fixed code if `--fix` is passed in but no changes are needed?

**Comment by fsouza** [comment]
@charliermarsh yeah, in general that's what tools do. Some examples of tools that do that include gofmt, autoflake and black:

```shell
# gofmt with code that needs fixing
％ echo "package               main\n\n\n" | gofmt
package main
```

```shell
# gofmt with code that doesn't need fixing
％ echo "package main" | gofmt
package main
```

```shell
# autoflake with code that needs fixing
％ echo "import os\nprint('hi')" | autoflake --remove-all-unused-imports -
print('hi')
```

```shell
# autoflake with code that doesn't need fixing
％ echo "import os\nprint(os.linesep)" | autoflake --remove-all-unused-imports -
import os
print(os.linesep)
```

```shell
# black with code that needs fixing
％ echo "import os\nprint(         os.linesep)" | black --quiet -
import os

print(os.linesep)
```

```shell
# black with code that doesn't need fixing
％ echo "import os\n\nprint(os.linesep)" | black --quiet -
import os

print(os.linesep)
```

**Comment by harupy** [comment]
Tweaked the source code to write the fixed code to stdout and tested it with VSCode:

https://user-images.githubusercontent.com/17039389/195140097-824c403a-20a4-459d-8674-b36c7860cf18.mov

Worked like a charm.

**Comment by charliermarsh** [comment]
Extremely cool. Maybe we write to `stdout` if `--fix` is passed in, but otherwise write back the errors...?

**Comment by charliermarsh** [comment]
Or maybe we move that behind an entirely separate subcommand.

**Comment by fsouza** [comment]
I like the idea of reusing `--fix`

**Comment by harupy** [comment]
+1 to reusing `--fix`

**Comment by fsouza** [comment]
@harupy I love your demo. Do you plan on sending a PR for that? If not I can send a PR.

**Pull request merged**
