### PR TITLE
[`pycodestyle`] Add `E201`, `E202`, `E203` Rule

### PR DESCRIPTION
**Pull request by saadmk11**
ref https://github.com/charliermarsh/ruff/issues/1073

### CODE REVIEW

**Comment by saadmk11** [comment]
Hi @charliermarsh, Is there a way to iterate over logical lines on Ruff? We need to use logical lines here instead of physical.

**Comment by charliermarsh** [comment]
Not at present but I implemented it once in #1130. We could consider reviving it. My main concern is that it's pretty slow (it should be faster now that we changed the `Locator` implementation) so I'm hesitant to turn on rules that require it by default.

We could consider changing the default ruleset to be explicitly those rules from Flake8 that are relevant when Black is enabled (instead of all `E` and `F` rules), which would help with that problem. Although most users would probably still end up enabling `E` and unknowingly pay the performance penalty. What do you think?

**Comment by ngnpope** [comment]
Perhaps instead of `--select ALL` we can have a `--select ALL-EXCEPT-RULES-HANDLED-BY-AUTOFORMATTER` ™ 😆 

Yeah - struggling on naming that one...

This would be particularly useful when `ruff` grows its own autoformatting support. Perhaps, if `ruff` knows that autoformatting is enabled it could still use `ALL` and just silently ignore those rules it doesn't need to run.

**Comment by saadmk11** [comment]
> Not at present but I implemented it once in #1130. We could consider reviving it. My main concern is that it's pretty slow (it should be faster now that we changed the `Locator` implementation) so I'm hesitant to turn on rules that require it by default.
> 
Currently the PR is using physical lines to check for issues which works perfectly with one line examples. But it requires logical lines to work on all scenarios and not raise false positives. Let me know if you revive #1130, I would be happy to test it out. but for now we can either close this PR (As it is dependent on a feature that is not implemented yet) or keep it as is. :)

> We could consider changing the default ruleset to be explicitly those rules from Flake8 that are relevant when Black is enabled (instead of all `E` and `F` rules), which would help with that problem. Although most users would probably still end up enabling `E` and unknowingly pay the performance penalty. What do you think?

Checking if black is enabled may proof to be inconsistent as it might be installed globally or installed in the current users virtualenv but not used for the project.

**Comment by charliermarsh** [comment]
Yeah I think we need logical lines for this to really be useful. We could try reviving that PR. I'm not sure what the performance characteristics will look like now.

**Comment by charliermarsh** [comment]
Let's close for now then, we can always reopen later.

**Pull request closed without merging**
