### PR TITLE
Show applied fixes by file and diagnostic

### LINKED ISSUE #2661: Add a flag to tell users which files were fixed, and via which rules

### PR DESCRIPTION
**Pull request by charliermarsh**
# Summary

Haven't bothered to fix up the tests yet, but here's the current UI:

Screen Shot 2023-02-09 at 10 24 05 PM

Once merged, closes #2661.

### CODE REVIEW

**Comment by charliermarsh** [comment]
@henryiii - This is just a first draft, but from your perspective, what's missing from the output?

You'd mentioned line numbers in the issue, but line numbers are a little tricky to include here, because they won't map to lines in the changed file, and they might not even map to line numbers in the _original_ file, because we preform multiple autofix passes. That is: sometimes, fixing a rule introduces a new violation, so we continue autofixing until the code stabilizes (e.g., if we remove a statement, it might render an import unused, and so on).

**Comment by charliermarsh** [comment]
We _could_ include the location information and message for every fixed violation, but the outputs are going to be confusing in some cases due to the above disclaimer.

**Comment by charliermarsh** [comment]
What if we included the human-readable name alongside the code, like `unused-variable`, etc.?

**Comment by ngnpope** [comment]
This is nice. Agreed that it probably doesn't make sense to give line/character breakdown. If you're removing lines, then there is no line to reference. And then it seems strange to have some with that information and some without.

Can I propose something like the following for the output?

```
Fixed 81 errors:
  crates/ruff/resources/test/fixtures/flake8_return/RET504.py:
     1 × E731 Do not assign a `lambda` expression, use a `def`
  crates/ruff/resources/test/fixtures/flake8_return/RET505.py:
    26 × F841 Local variable `…` is assigned to but never used
  crates/ruff/resources/test/fixtures/flake8_return/RET506.py:
    19 × F841 Local variable `…` is assigned to but never used
  crates/ruff/resources/test/fixtures/flake8_return/RET507.py:
    16 × F841 Local variable `…` is assigned to but never used
  crates/ruff/resources/test/fixtures/flake8_return/RET508.py:
    19 × F841 Local variable `…` is assigned to but never used
```

This makes it easy to parse as things align nicely. Some thoughts:

- Sort the outer list of files alphabetically - it's easier to scan through
- Sort the inner lists by decreasing number of fixes - it's nice to know where the biggest wins were
- Output the rule message to avoid having to look up rule codes
  - Note that rules with more than one message format should be grouped separately, e.g.

    ```
      1 × RUF100 Unused blanket `noqa` directive
     10 × RUF100 Unused `noqa` directive
    100 × RUF100 Unused `noqa` directive (…)
    ```
  - But don't repeat for all variations of a message, i.e. substitute `…` for all placeholders
- Right align the count of violations fixed under _all_ files by the number of digits for the biggest number
- And I love the use of nice unicode symbols... So note the `×` and `…` 😉

**Comment by charliermarsh** [comment]
I'm hesitant to include the message formats because they're not very clear in a lot of cases, and we haven't committed to maintaining variants that _would_ be clear in this context. I'd kind of prefer to use the human-readable rule name for that purpose, which we _are_ committed to maintaining.

**Comment by ngnpope** [comment]
(Sorry - am crossing comments. Bad timing! 😅 )

**Comment by ngnpope** [comment]
> Also, we lose a bit of context when a rule has different messages.

Although maybe this is an indication that a rule should be split up into multiple rules? 🤔

**Comment by charliermarsh** [comment]
(This'll go out in the next release, not tonight's.)

**Pull request merged**
