### PR TITLE
GH-Action

### PR DESCRIPTION
**Pull request by brucearctor**
Accidentally closed:  https://github.com/charliermarsh/ruff/pull/3756 ( and didn't seem like I was able to re-open it )

Addresses:  https://github.com/charliermarsh/ruff/issues/3289

### CODE REVIEW

**Comment by ssweber** [comment]
(this open pull is missing the docs. didn’t know if that was intentional or an oversight)

**Comment by charliermarsh** [comment]
Ok, sorry for the back-and-forth on this, but I've discussed it with @MichaReiser and @konstin and we've decided that we'd prefer to use a Pyright-like setup. That is, we'd prefer to put the action in https://github.com/charliermarsh/ruff-action, and point to it from the docs. The benefit is that we can version the action separately. As-is, we wouldn't really have any way to signal changes in the action's API or configuration, since it'd be coupled to Ruff versions.

Are you open to PR'ing the action YAML in that repo, and then docs here? Then I can publish it to the Marketplace?

**Comment by brucearctor** [comment]
> (this open pull is missing the docs. didn’t know if that was intentional or an oversight)

Oversight ...

**Comment by brucearctor** [comment]
> Ok, sorry for the back-and-forth on this, but I've discussed it with @MichaReiser and @konstin and we've decided that we'd prefer to use a Pyright-like setup. That is, we'd prefer to put the action in https://github.com/charliermarsh/ruff-action, and point to it from the docs. The benefit is that we can version the action separately. As-is, we wouldn't really have any way to signal changes in the action's API or configuration, since it'd be coupled to Ruff versions.
> 
> Are you open to PR'ing the action YAML in that repo, and then docs here? Then I can publish it to the Marketplace?

OK - can mimick pyright setup.

**Comment by brucearctor** [comment]
Array vs String.  Where are people at on preference, @MichaReiser , @charliermarsh , @konstin ?  Ex: https://github.com/charliermarsh/ruff/pull/3756#discussion_r1151500881 ...

I imagine better to just put in place what is most desired than needing to refactor/version-bump to accommodate.

**Comment by brucearctor** [comment]
That works: I'll get things cleaned up and PR together - if not today should be able to address over the weekend.  Naturally, if others have strong opinions for another course of action, please share.

**Comment by charliermarsh** [comment]
Thank you, and no rush. I know it might be a little frustrating to have back-and-forth but API decisions like this tend to be an iterative process as we build agreement. Really appreciate your work here.

**Comment by brucearctor** [comment]
This is nothing new, API discussions generally need to occur and consensus built - esp. for a public facing interface that shouldn't have breaking changes too often.  

Plenty familiar as I'm a committer and [PMC](https://www.apache.org/dev/pmc.html) member ( or equivalent ) on a number of OSS projects [ esp [ASF](https://www.apache.org/) ], and often guide OSS journeys, or lead intro to OSS trainings.  It just takes a little bit to figure out how people want to work/collaborate.

**Comment by brucearctor** [comment]
Upon further reflection, I think we should go with `args` ...  `extra-args` seems slightly/potentially confusing.  "Extra" has the connotation of more/additional, yet the args would become the args not append to something existing.  Sound good @charliermarsh ?  

Anything else you can think of?  Otherwise, should be able to mimic pyright setup easily.  THEN can follow up with more improvements, additional docs [ ex: to cover the not basic use-cases, etc ]

**Comment by ssweber** [comment]
Is there a good reason to split up the command line args?

hope I’m not being a bother.

```
with:
    command-line-args: “check .”

**Comment by brucearctor** [comment]
@ssweber -- Comments welcome, at least for consideration.

```yaml
name: Ruff

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: charliermarsh/ruff@v0
```

^^ as written that runs `ruff check .`


```yaml
name: Ruff

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: charliermarsh/ruff@v0
        with:
            src: /path/to/code/
```

^^ would run `ruff check /path/to/code/`

```yaml
name: Ruff

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: charliermarsh/ruff@v0
        with:
            args: --select ANN
```

would run `ruff --select ANN .`

etc.  

Then you can update either the path, or the args ( or version ) independent of eachother.  Why would I want to have to specify a '.' if that's the most likely setting for users, it is a nice default and better to not have to mention unless wanting to override.  Naturally, I'll cleanup docs to include these things.

Did that answer your question?

**Comment by ssweber** [comment]
Yes, thank you for the detailed response!

**Pull request closed without merging**
