### PR TITLE
[`pylint`]: Implement `while-used` (`W0149`)

### PR DESCRIPTION
**Pull request by latonis**
Rule reference: https://pylint.pycqa.org/en/latest/user_guide/messages/warning/while-used.html

Implemented for #970 

Implemented exactly as Pylint does, which is to flag every single `while` loop if this is enabled :smile_cat:

### CODE REVIEW

**Comment by charliermarsh** [comment]
One challenge with this rule is that in Pylint, you typically have to enable it explicitly (I think?) by enabling the `pylint.extensions.while_used` checker. We don't have a great mechanic for that, so all users that have Pylint enabled would be opted into this 🤔

**Comment by latonis** [comment]
> One challenge with this rule is that in Pylint, you typically have to enable it explicitly (I think?) by enabling the `pylint.extensions.while_used` checker. We don't have a great mechanic for that, so all users that have Pylint enabled would be opted into this thinking

Ah fair point @charliermarsh, could we add an config option for Pylint like `while_used` to be set to true that way it only runs when the user has it enabled, similar to how the user would be enabling it with `extensions.while_used` in standard Pylint?

**Comment by latonis** [comment]
@charliermarsh, I've added a config option via Pylint's `Options` struct to try to simulate the `pylint.extension` needing to be enabled too. If this route isn't the way you'd like to head and this rule is too opinionated I understand not implementing :smile_cat:

**Comment by charliermarsh** [comment]
That's a clever solution... Even _with_ that, I think I'm gonna err on the side of skipping this one. The issue is we now have two ways to "turn on" the rule -- e.g., if a user does `--select PLW0149`, the rule actually wouldn't turn on, which feels unintuitive. But it _also_ feels unintuitive for that to turn on the rule despite the presence of this extension setting!

**Comment by charliermarsh** [comment]
BTW -- you're definitely welcome to keep picking off Pylint or other rules, but if it'd be ever helpful to get alignment before putting in the work, I'm always happy to chime in and confirm or discuss etc., either via comments in any relevant issue or on Discord. It's totally up to you, it just always hurts to close people's PRs or reject proposals after folks have put in good work :(

**Comment by latonis** [comment]
> BTW -- you're definitely welcome to keep picking off Pylint or other rules, but if it'd be ever helpful to get alignment before putting in the work, I'm always happy to chime in and confirm or discuss etc., either via comments in any relevant issue or on Discord. It's totally up to you, it just always hurts to close people's PRs or reject proposals after folks have put in good work!

I appreciate that, I've been jumping in head first into the Ruff ecosystem and it's allowing me to learn Rust and be able to contribute to a great community and project, so I've just started working on them first and have no hard feelings on closing a PR :smile: . However, will definitely ping you in the future if the rule seems very opinionated or noisy on how you'd like to proceed with it :smile:

**Comment by charliermarsh** [comment]
For sure, I've really appreciated all your contributions this far! I hope it's been a good experience!

(FWIW, in general, I'm happy to add anything on the Pylint list, but am wary of adding those rules that are part of Pylint _extensions_ which is typically buried at the bottom of the page for the relevant rule.)

**Pull request closed without merging**
