### PR TITLE
Enable `pycodestyle` rules

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This PR enables the `pycodestyle` rules by removing the `logical_lines` feature flag. Based on @MichaReiser's great work, these rules only increase the CPython benchmark by about 25% in my local testing (let's see what the CI benchmarks say), and some 10s of milliseconds of that is a result of "more violations" (rather than actual analysis).

One major decision we should make is whether we want to include these rules in the default ruleset. Right now, the default ruleset is `["E", "F"]`. But we could change it to `["E4", "E5", "E7", "E9", "F"]` to represent "Those Pyflakes rules that are obviated by Black", which would also avoid any performance regressions for users on the default settings (and in theory for those that configure Ruff by starting with the defaults and iterating from there).

### CODE REVIEW

**Comment by MichaReiser** [comment]
Hmm, this is still kind of a lot. If I remember correctly than half of the regression is just due to the fact that we need to build the locator index.

Let me have a stab at adding a byte-location feature to RustPython tomorrow afternoon. Do you know if we make much use of the location row/column information outside of printing diagnostics?

Note: using byte offsets can regress performance for projects with many diagnostics because we have to compute the line index if there's a single diagnostic regardless if any rule uses the source. But it should give us better performance for projects that have only a few diagnostics, which is the majority of projects that are using Ruff

**Comment by MichaReiser** [comment]
Let's see how this does in terms of performance after rebasing on top of #3931

**Comment by MichaReiser** [comment]
Nice! A 10% regression (compared to up to 50% before) is way more reasonable.

**Review by MichaReiser — APPROVED** [review]
Should we announce the new rules as experimental or do we feel confident they match pycodestyle? If we announce them as experimental, should we remove them from the pycodestyle group for now and ask users to explicitly opt-in?

**Comment by MichaReiser** [comment]
I'm considering creating a new `nursery` group where we can add any new rules that we aren't confident to roll out directly and must be enabled explicitly (they are not included in `ALL`).

**Comment by MichaReiser** [comment]
This is huge. 🎸🎸🎸

**Comment by danieleades** [comment]
i see `E704` is ticked off the list, but i don't see it mentioned [in the docs](https://docs.astral.sh/ruff/rules/#error-e). what's the status of this rule?

**Comment by AA-Turner** [comment]
E704 was removed in #2773, and remains gone as far as I can tell -- or I have previously missed it in the preview rules.

A

**Pull request merged**
