### PR TITLE
Fix E402 false positive

### PR DESCRIPTION
**Pull request by carlosmiei**
Hello guys :) This is my first contribution to this fantastic project, sorry if I'm missing something. (I tried to follow all the `Contributing` recommendations)
- fixes https://github.com/charliermarsh/ruff/issues/3010

### CODE REVIEW

**Comment by JonathanPlasse** [comment]
You got a fix fast! :+1:

**Comment by charliermarsh** [comment]
Thank you! Asked one question in #3010 that I'd like to resolve before proceeding :)

**Comment by carlosmiei** [comment]
> Thank you! Asked one question in #3010 that I'd like to resolve before proceeding :)

Sure, let me know if anything :)

**Comment by charliermarsh** [comment]
Ok, I think for now, we should leave the current behavior as-is. My read is that the intent of pydocstyle is to only skip _docstrings_, and a multi-line string included after an import isn't a docstring.

If pydocstyle allowed _this_, then I'd be more convinced:

```py
"""abc """
"""def """
import os
```

But they flag that as an error, and indeed Python doesn't treat the second string as a docstring.

Thank you so much for the PR but I'm going to forego for now. I hope you continue contributing, it'd be great to have you involved!

**Pull request closed without merging**
