### PR TITLE
Implement `asyncio-dangling-task` to track `asyncio.create_task` calls

### LINKED ISSUE #2809: New rule: warning accidental garbage collection of `asyncio.create_task`
I wanted to purpose a new lint rule. The `asyncio.create_task` function has a caveat, which is when you create a task in order to make sure it finishes you need to take a reference to it.
image

I first read about this in [this post](https://textual.textualize.io/blog/2023/02/11/the-heisenbug-lurking-in-your-async-code/). Which also sites a lot of projects that are doing this wrong.

Is this something that ruff wants to support? I could give it a try to implement it in that case.

### PR DESCRIPTION
**Pull request by charliermarsh**
This rule guards against `asyncio.create_task` usages of the form:

```py
asyncio.create_task(coordinator.ws_connect())  # Error
```

...which can lead to unexpected bugs due to the lack of a strong reference to the created task. See Will McGugan's blog post for reference: https://textual.textualize.io/blog/2023/02/11/the-heisenbug-lurking-in-your-async-code/.

Note that we can't detect issues like:

```py
def f():
    # Stored as `task`, but never used...
    task = asyncio.create_task(coordinator.ws_connect())
```

So that would be a false negative. But this catches the common case of failing to assign the task in any way.

Closes #2809.

### CODE REVIEW

**Comment by charliermarsh** [comment]
@akx - I notice that `home-assistant/core` has a couple of these. If you have a sec -- do those look like false positives? Or do they look correct? Just trying to do some real-world evaluation prior to merging.

```
❯ cargo run ../core --select RUF006 -n
   Compiling ruff v0.0.247 (ruff/crates/ruff)
   Compiling ruff_cli v0.0.247 (ruff/crates/ruff_cli)
    Finished dev [unoptimized + debuginfo] target(s) in 9.11s
     Running `target/debug/ruff ../core --select RUF006 -n`
core/homeassistant/components/apple_tv/__init__.py:225:13: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/august/__init__.py:191:13: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/bluetooth_le_tracker/device_tracker.py:188:17: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/cast/media_player.py:191:9: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/crownstone/entry_manager.py:91:9: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/elkm1/__init__.py:190:5: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/google/calendar.py:475:9: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/homeassistant/__init__.py:157:13: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/homeassistant/__init__.py:180:13: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/homekit/type_cameras.py:446:13: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/insteon/__init__.py:175:5: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/livisi/__init__.py:44:5: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/mysensors/gateway.py:119:13: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/plum_lightpad/light.py:54:5: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/roon/server.py:69:9: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/sense/__init__.py:127:5: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/smart_meter_texas/__init__.py:81:5: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/sonos/__init__.py:481:9: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/squeezebox/media_player.py:173:5: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/squeezebox/media_player.py:206:9: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/unifiprotect/discovery.py:37:5: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/websocket_api/decorators.py:45:9: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/wiz/__init__.py:54:5: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/wled/coordinator.py:98:9: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/zeroconf/__init__.py:396:9: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/zha/core/channels/security.py:353:13: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/zha/core/gateway.py:256:9: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/components/zha/light.py:593:17: RUF006 `asyncio.create_task` call without a reference to the returned task
core/homeassistant/util/timeout.py:224:13: RUF006 `asyncio.create_task` call without a reference to the returned task
core/tests/test_runner.py:130:9: RUF006 `asyncio.create_task` call without a reference to the returned task
Found 30 errors.
```

**Comment by akx** [comment]
Ooh, hey, @frenck, want to chip in on those home-assistant issues? By random sampling they look like they might be genuine bugs..?

**Comment by frenck** [comment]
@charliermarsh We are aware, we started working on it actually. 
See: <https://github.com/home-assistant/core/pull/87970>

This rule would help us a lot to guard it btw, so it is more than welcome 👍 

../Frenck

**Comment by charliermarsh** [comment]
Awesome! Thank you for chiming in! Mostly just wanted to sanity-check that it wasn't totally off-base on real-world code :)

**Comment by frenck** [comment]
No problem, feel free to ping me in such cases. Thanks for the awesome project btw ❤️

**Comment by charliermarsh** [comment]
@frenck - Thank you so much ❤️ I totally missed 2.5k, it's so cool to see the project come this far!

**Pull request merged**
