### PR TITLE
Adds flake8-builtins

### PR DESCRIPTION
**Pull request by sobolevn**
I mark this as a WIP, because I don't have `rust` on my machine right now **because of the SECURITY reasons** 😒 

So, I've never actually executed the code I wrote.
Plus, I need to write tests.

Original source: https://github.com/gforcada/flake8-builtins/blob/22566d388b9ac0a87ec2efc8d7be95c3303ed651/flake8_builtins.py

### CODE REVIEW

**Comment by charliermarsh** [comment]
Looking good! Do you plan to run + test + get it out of draft state? Or want a hand given the above comment RE installing Rust?

**Comment by sobolevn** [comment]
I actually had to find a way to run this to find proper `column` numbers 🙈 
It was fun writting code without ever running it!

**Comment by charliermarsh** [comment]
Hahaha I don't understand how you did this

**Comment by charliermarsh** [comment]
Code looks great, merging shortly...

**Pull request merged**
