### PR TITLE
Make some pydocstyle rules respect line continuation character

### PR DESCRIPTION
**Pull request by yuxqiu**
Currently, pydocstyle rules produce many false positives on code bases that use continuation characters in docstrings. This PR tries to make some pydocstyle rules respect line continuation character. 

Progress so far
- [ ] fix D205 and add one more auto fix
    - Need to respect [stringescapeseq](https://docs.python.org/3/reference/lexical_analysis.html#grammar-token-python-grammar-stringescapeseq)

After a quick look, I plan to investigate the following rules as they may have the same problem.
- [ ] D200 (empty first line + content -> no report)
- [ ] D209
- [ ] D210 (?)
- [ ] D400
- [ ] D415

### CODE REVIEW

**Comment by charliermarsh** [comment]
Do you know if `pydocstyle` itself treats continuations in this way? As in, would we be intentionally deviating from `pydocstyle` by merging this? Or does Ruff _currently_ differ from `pydocstyle` here?

**Comment by yuxqiu** [comment]
> 

As far as I know, `pydocstyle` treats continuations in this way. When I run `pydocstyle crates/ruff/resources/test/fixtures/pydocstyle/D205.py --select D205`, it prints

```
crates/ruff/resources/test/fixtures/pydocstyle/D205.py:13 in public function `f3`:
D205: 1 blank line required between summary line and description (found 0)
crates/ruff/resources/test/fixtures/pydocstyle/D205.py:30 in public function `f5`:
D205: 1 blank line required between summary line and description (found 0)
crates/ruff/resources/test/fixtures/pydocstyle/D205.py:42 in public function `f6`:
D205: 1 blank line required between summary line and description (found 3)
```

But when I run `ruff check rates/ruff/resources/test/fixtures/pydocstyle/D205.py --select D205` (without this PR), it produces 3 false positives:

```
crates/ruff/resources/test/fixtures/pydocstyle/D205.py:2:5: D205 1 blank line required between summary line and description
crates/ruff/resources/test/fixtures/pydocstyle/D205.py:7:5: D205 1 blank line required between summary line and description
crates/ruff/resources/test/fixtures/pydocstyle/D205.py:13:5: D205 1 blank line required between summary line and description
crates/ruff/resources/test/fixtures/pydocstyle/D205.py:19:5: D205 1 blank line required between summary line and description
crates/ruff/resources/test/fixtures/pydocstyle/D205.py:30:5: D205 1 blank line required between summary line and description
crates/ruff/resources/test/fixtures/pydocstyle/D205.py:42:5: D205 1 blank line required between summary line and description
```

**Comment by yuxqiu** [comment]
@charliermarsh Considering how Python escape string literals, I think we can provide a function in `crates/ruff_python_ast/src/str.rs` to unescape strings. After that, we can easily handle line continuation and newlines. What do you think?

**Comment by charliermarsh** [comment]
Going to close in the interest of keeping the PR list up-to-date. Can always re-open if we choose to revisit!

**Pull request closed without merging**
