### PR TITLE
Add flake8-debugger

### PR DESCRIPTION
**Pull request by karpa4o4**

### CODE REVIEW

**Comment by karpa4o4** [comment]
@charliermarsh, hi. I tried to bring the logic as close to the original as possible, but in debugger_call it was not completely successful. I will be glad to receive feedback.

**Comment by charliermarsh** [comment]
Awesome! Will review this shortly. Thanks for putting this together.

**Comment by charliermarsh** [comment]
@karpa4o4 - I did some small refactors to use `match_call_path` and friends, which are some utilities we have to do this kind of "Is a function call an invocation of a specific member, in a specific module?" logic.

**Comment by charliermarsh** [comment]
But let me know if I messed anything up please :)

**Comment by karpa4o4** [comment]
@charliermarsh, thanks. Sorry, I forgot to write "Closed" in the pull request description. So issue [#546](https://github.com/charliermarsh/ruff/issues/546) stays open.
Can I help with the implementation of some other rule?

**Comment by charliermarsh** [comment]
Oh good catch! Just closed the issue.

> Can I help with the implementation of some other rule?

Definitely! There's a bunch of unclaimed stuff in https://github.com/charliermarsh/ruff/issues/827, if you're interested in those? Alternatively, there's https://github.com/charliermarsh/ruff/issues/458 but it's a bit more involved as I'd like it to be integrated with some of the existing docstring checks.

**Comment by charliermarsh** [comment]
Oh, or https://github.com/charliermarsh/ruff/issues/870 -- we only need the first rule (U100). It'd probably look like the implementation we have for `unused_variables`, but we have to check for `BindingKind::Argument`.

**Comment by karpa4o4** [comment]
@charliermarsh, hi. Unfortunately I could not do the issues that you described above. But now I want to participate in the development of ruff again, can you tell me how I can help?

**Comment by charliermarsh** [comment]
No worries! If you're interested, you could consider working on the [`tryceratops`(https://github.com/charliermarsh/ruff/issues/2056) plugin.

**Pull request merged**
