### PR TITLE
Implement `flake8-errmsg`

### PR DESCRIPTION
**Pull request by edgarrmondragon**
Closes https://github.com/charliermarsh/ruff/issues/1255

### CODE REVIEW

**Comment by charliermarsh** [comment]
@edgarrmondragon - I think the Black test failure is mine.

**Comment by charliermarsh** [comment]
Err, wait, no, maybe not?

**Comment by edgarrmondragon** [comment]
> Err, wait, no, maybe not?

It's mine 😅

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon - I think the Black test failure is mine.

@charliermarsh It's fixed now :)

**Comment by charliermarsh** [comment]
Looks great! 🎸

**Comment by ofek** [comment]
Wow thanks!

**Pull request merged**
