### PR TITLE
Introduce ruff::rules module

### LINKED ISSUE #1547: Introduce a Rust module for all lint implementations
The code is currently split up across the following Rust modules:

* ast
* autofix
* cache
* checkers
* checks
* checks_gen
* cli
* commands
* cst
* directives
* docstrings
* eradicate
* flake8_2020
* flake8_annotations
* flake8_bandit
* flake8_blind_except
* flake8_boolean_trap
* flake8_bugbear
* flake8_builtins
* flake8_comprehensions
* flake8_datetimez
* flake8_debugger
* flake8_errmsg
* flake8_implicit_str_concat
* flake8_import_conventions
* flake8_print
* flake8_quotes
* flake8_return
* flake8_simplify
* flake8_tidy_imports
* flake8_unused_arguments
* fs
* isort
* iterators
* lex
* lib_native
* linter
* logging
* mccabe
* message
* noqa
* packages
* pandas_vet
* pep8_naming
* printer
* pycodestyle
* pydocstyle
* pyflakes
* pygrep_hooks
* pylint
* python
* pyupgrade
* resolver
* ruff
* rustpython_helpers
* settings
* source_code_generator
* source_code_locator
* source_code_style
* updates
* vendor
* visibility

62 top-level modules is a lot and makes the codebase hard to grasp and navigate, so I recommend moving all modules that implement specific rules/checks/lints ([whatever we call  them](https://github.com/charliermarsh/ruff/issues/1546)) under a common  module, so for example:

* lints
  * eradicate
  * flake8_2020
  * flake8_annotations
  * flake8_bandit
  * flake8_blind_except
  * flake8_boolean_trap
  * flake8_bugbear
  * flake8_builtins
  * flake8_comprehensions
  * flake8_datetimez
  * flake8_debugger
  * flake8_errmsg
  * flake8_implicit_str_concat
  * flake8_import_conventions
  * flake8_print
  * flake8_quotes
  * flake8_return
  * flake8_simplify
  * flake8_tidy_imports
  * flake8_unused_arguments
  * isort
  * mccabe
  * pandas_vet
  * pep8_naming
  * pycodestyle
  * pydocstyle
  * pyflakes
  * pygrep_hooks
  * pylint
  * pyupgrade
  * ruff

So e.g. `ruff:flake8_builtins` would become `ruff:rules:flake8_builtins`, `ruff:ruff` would become `ruff:rules:ruff`, etc.

### PR DESCRIPTION
**Pull request by not-my-profile**
Resolves #1547.

### CODE REVIEW

**Comment by not-my-profile** [comment]
Huh, that's interesting apparently GitHub's file move detection is worse than git's file move detection ... if you `git show` the second commit `git` reports:

> 1247 insertions(+), 1247 deletions(-)

whereas the GitHub UI apparently just gives up and claims

> +39,491 −39,492

**Comment by charliermarsh** [comment]
Cool.

Is it at all strange that we have (e.g.):

- `rules::flake8_quotes::rules` (rules twice)
- `rules::flake8_quotes::settings` (`rules` module includes settings)

Do you see this changing further in future commits?

**Comment by not-my-profile** [comment]
Yes I think the duplicate "rules" could be changed to `rules::{origin}::{specific_rule}`.

I don't really mind the settings under rules since the settings are for the rules ... potentially the settings could be moved to `mod.rs` and the tests out of  `mod.rs`.

**Comment by charliermarsh** [comment]
Ok cool. Do you mind rebasing, and I'll merge this next? Apologies.

**Comment by not-my-profile** [comment]
Of course, no worries :) Rebased.

**Comment by charliermarsh** [comment]
Thanks!

**Comment by not-my-profile** [comment]
(btw I sent you an email yesterday)

**Pull request merged**
