### PR TITLE
[`flake8-bandit`]: Implement deny-list rules for suspicious member calls

### PR DESCRIPTION
**Pull request by colin99d**
ref: #1646

@charliermarsh the different violations have different severities. Would you like me to add a setting that lets users only see errors above a certain severity?

### CODE REVIEW

**Comment by charliermarsh** [comment]
@colin99d - Na we need to tackle severities more holistically, I think. We could consider adding a severity level for all of bandit...?

**Comment by charliermarsh** [comment]
Since AFAIK all Bandit rules have some notion of severity.

**Comment by colin99d** [comment]
I think adding severity into this rule, and then eventually to all the other ones slowly makes a lot of sense. Then we can just make a bandit-wide (and maybe eventually have this work with other rule sets) rule.

**Comment by colin99d** [comment]
@charliermarsh, ready!

**Comment by MichaReiser** [comment]
Do we inherit this name from `flake8`? If not, then I recommend renaming the rule to `denylist_calls` to be more inclusive.

**Comment by charliermarsh** [comment]
Agreed. Even if it's inconsistent with Bandit, we should still change it. (I believe we've done that in the past.)

**Pull request merged**
