### PR TITLE
Update RustPython to use the correct `BinOp` location

### PR DESCRIPTION
**Pull request by harupy**
See https://github.com/RustPython/RustPython/pull/4348

```shell
# On main
> cargo run -- --show-source resources/test/fixtures/pyflakes/F504.py
...
resources/test/fixtures/pyflakes/F504.py:3:15: F504 '...' % ... has unused named argument(s): b
  |
3 | "%(a)s %(c)s" % {a: "?", "b": "!"}  # F504 ("b" not used)
  |               ^^^^^^^^^^^^^^^^^^^^ F504
  |
resources/test/fixtures/pyflakes/F504.py:8:9: F504 '...' % ... has unused named argument(s): b
  |
8 | "%(a)s" % {"a": 1, r"b": "!"}  # F504 ("b" not used)
  |         ^^^^^^^^^^^^^^^^^^^^^ F504
  |
resources/test/fixtures/pyflakes/F504.py:9:9: F504 '...' % ... has unused named argument(s): b
  |
9 | "%(a)s" % {'a': 1, u"b": "!"}  # F504 ("b" not used)
  |         ^^^^^^^^^^^^^^^^^^^^^ F504
  |
Found 3 error(s).
3 potentially fixable with the --fix option.
```

```shell
# On this PR branch
> cargo run -- --show-source resources/test/fixtures/pyflakes/F504.py
...
resources/test/fixtures/pyflakes/F504.py:3:1: F504 '...' % ... has unused named argument(s): b
  |
3 | "%(a)s %(c)s" % {a: "?", "b": "!"}  # F504 ("b" not used)
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ F504
  |
resources/test/fixtures/pyflakes/F504.py:8:1: F504 '...' % ... has unused named argument(s): b
  |
8 | "%(a)s" % {"a": 1, r"b": "!"}  # F504 ("b" not used)
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ F504
  |
resources/test/fixtures/pyflakes/F504.py:9:1: F504 '...' % ... has unused named argument(s): b
  |
9 | "%(a)s" % {'a': 1, u"b": "!"}  # F504 ("b" not used)
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ F504
  |
Found 3 error(s).
3 potentially fixable with the --fix option.
```

### CODE REVIEW

**Comment by harupy** [comment]
btw do we have a script or command in this repository that can update snapshots quickly?

```shell
> cargo test
# generates new snapshots if there are failed tests

> ???
# Updates existing snapshots

```

**Comment by charliermarsh** [comment]
Do you have `cargo-insta` installed? Have you tried running `cargo insta review`?

https://crates.io/crates/cargo-insta

**Comment by charliermarsh** [comment]
(Apologies if misunderstanding the question.)

**Comment by harupy** [comment]
@charliermarsh `cargo insta review` is what I've looking for. Thanks!

**Comment by charliermarsh** [comment]
@harupy - Oh no!!! I wish you'd known about it before! I had no idea you were doing it manually. Hopefully it'll save you a _ton_ of time.

**Comment by harupy** [comment]
I wrote a shell script that and have been using it :)

```
```

**Pull request merged**
